### ISSUE TITLE
How to use in multi-stage builds?

### ISSUE THREAD

**Issue by tadejsv** [mamba-org/micromamba-docker#10]
What's the best way to use this image in multi-stage builds?

I'm interested in applications where the first stage is to create an environment using `micromamba`, and then in the secod stage, with a different base image, that environment is copied to the new image. For example if the second stage needs to be a `nvidia/cuda` based image, etc. Like the following

```
FROM mamabaorg/micromamba AS micromamba
# Create env here

FROM new_base
COPY --from=micromamba ???
# set some env vars, bashrc?
```

**Comment by wolfv** [comment]
https://uwekorn.com/2021/03/01/deploying-conda-environments-in-docker-how-to-do-it-right.html

same idea probably?

**Comment by tadejsv** [comment]
Great resource, thanks!
