### ISSUE TITLE
Add conda-lock example to README

### ISSUE THREAD

**Issue by maresb** [mamba-org/micromamba-docker#100]
In order to be able to reproduce image builds, one really should render the environment specification into a lockfile before building, and then use the lockfile (and *not* the environment specification) during build to set up the environment with micromamba.

I think it would suffice to add a section to "Advanced Usages".

**Comment by wholtz** [comment]
Yes, this sounds useful. I haven't used them myself yet, but looking through the mamba issue tracker, it looks like you are quite well versed.

**Comment by wholtz** [comment]
Done in #133
