### ISSUE TITLE
Use `ENTRYPOINT` with a python command raises `command not found`

### ISSUE THREAD

**Issue by igaloly** [mamba-org/micromamba-docker#101]
When I use a python command in an `ENTRYPOINT` layer at the end on my Dockerfile, I get `bash: line 1: python: command not found`

I would love to hear your insight if I've mistaken somewhere (or if the issue isn't related to Mamba) :)

This is my Dockerfile.
```
FROM mambaorg/micromamba:0.19.1

WORKDIR /app

ENV LISTEN_PORT 80

COPY --chown=micromamba:micromamba base-env.yaml base-env.yaml
RUN micromamba install -y -f base-env.yaml && \
    micromamba clean --all --yes
# (otherwise python will not be found)
ARG MAMBA_DOCKERFILE_ACTIVATE=1
COPY . .
WORKDIR ./src
ENTRYPOINT python -m service.start
```

**Comment by wholtz** [comment]
hi @igaloly -- thank you for your interest in micromamba. 

Running a program from a conda environment in the ENTRYPOINT seems like it would be a common use case but somehow it hasn't made it into our test suite yet. The best solution right now would be to replace your last line with:
```Dockerfile
ENTRYPOINT ["/usr/local/bin/_entrypoint.sh", "python", "-m", "service.start"]
```

It is critical that you use the 'exec' form of `ENTRYPOINT` as I have shown.

I'm going to investigate if there is a more automatic way the conda environment can be activated for the `ENTRYPOINT` command, but from the reading I've done so far, I'm not optimistic.

We do need to add some tests and documentation around this usage pattern.

**Comment by wholtz** [comment]
I should also mention that you do not need:
```Dockerfile
ARG MAMBA_DOCKERFILE_ACTIVATE=1
```
As the ENTRYPOINT commands do not run during the execution of `docker build ...`.

**Comment by igaloly** [comment]
Hi @wholtz, thanks for the quick and professional response!
Your suggestion works :)

I would love to hear from you about the underlying mechanism that prevented from `ENTRYPOINT python -m service.start` to work and let `ENTRYPOINT ["/usr/local/bin/_entrypoint.sh", "python", "-m", "service.start"]` work.

Moreover, I would love to understand how `ARG MAMBA_DOCKERFILE_ACTIVATE=1` lets the ability to `RUN` python commands at build-time.

**Comment by maresb** [comment]
@igaloly, going back to your original example, I would recommend simply replacing `ENTRYPOINT` by `CMD`. The `CMD` statement defines the default command to run from `docker run containername [command]` when no `command` is specified. I think that's directly in-line with what you expected.

The `ENTRYPOINT` command defines the default shell for the `docker run` command. By setting it to `_entrypoint.sh`, we provide an *activated* Bash shell.

The mechanism for `ARG MAMBA_DOCKERFILE_ACTIVATE=1` is accomplished via the `SHELL _shell.sh` command. Similar to `ENTRYPOINT`, the `SHELL` command defines the default shell for the `docker build` command.

Does this clear up all your questions?

@wholtz and I have been working on the README lately. We'd greatly appreciate any advice for how to make them more understandable!

**Comment by igaloly** [comment]
@maresb Definitely clears up my questions. You answered greatly. Thank you very much! :)

**Comment by wholtz** [comment]
> @igaloly, going back to your original example, I would recommend simply replacing `ENTRYPOINT` by `CMD`. The `CMD` statement defines the default command to run from `docker run containername [command]` when no `command` is specified. I think that's directly in-line with what you expected.

Using the `CMD` would preclude you from passing additional arguments for `service.start` on the command line. So if you need that functionality, then you'd have to stick with the `ENTRYPOINT` I proposed.
