### ISSUE TITLE
Permanently activating Micromamba in container using zsh

### ISSUE THREAD

**Issue by beatslikeahelix** [mamba-org/micromamba-docker#104]
So, I'm facing an issue in which I'm struggling to permanently activate Micromamba in a zsh shell.
I'm pulling the Micromamba Docker Hub image and installing Oh My Zsh afterwards using this method:
[https://github.com/deluan/zsh-in-docker](url)
Following the advice from `micromamba --help` regarding permanently initialising the shell, I can get things to work temporarily.
I can use `micromamba activate` /  `micromamba deactivate`, and my environment is correctly found with `micromamba list`.
However, if I then open up a new terminal in VS Code, things begin to fall apart. I need to repeat my actions for `activate` and `deactivate` to become available, and my environment is no longer correctly found with `list`.
I imagine this is somewhat related to `MAMBA_ROOT_PREFIX` but I'm too much of a n0ob to Linux & Docker to figure it out.

Any friendly words of advice here? Should I be pulling from the Micromamba base image at all if I intend to work with zsh, or should I build my own image from Debian-Slim like in your Dockerfile?

Much obliged for the great work.

**Comment by wholtz** [comment]
Hello @beatslikeahelix -- thank you for the interest in micromamba. 

This project is some what new and we have rather limited developer resources, so for now we are focusing on supporting the bash shell. I would welcome a pull request to that adds zsh support if that is something you'd be interested in doing.  I haven't looked at how zsh shell startup differs from bash, so it is currently unclear to me how much work is involved. 

Is it a firm requirement that you need to use zsh? If you can get away with bash, we will be able to offer more help....

If you have to stick with zsh, you could try replacing all instances of `.bashrc` with `.zshrc` with in this repo and then build your own micromamba image. I'm guessing that will get fairly far.

**Comment by wholtz** [comment]
Closing as we will not be implementing zsh support at this time. Hopefully it will be added a later date.
