### ISSUE TITLE
command pip not found

### ISSUE THREAD

**Issue by stevemarin** [mamba-org/micromamba-docker#107]
Hello!  Happy holidays!  I just ran into some issues with the 0.19.1 micromamba image on Docker Hub.  I'm getting the error "command pip not found" when I mamba-install dependencies and then try to pip install a local package copied to the Docker container.

```
RUN micromamba install -y -n base -f /fled/env.yaml && \
    pip install /fled && \
    micromamba clean --all --yes
```

where `env.yaml` is:

```
name: base
channels:
  - conda-forge
dependencies:
  - python=3.9
  - sqlmodel
  - fastapi
  - pandas
  - networkx
  - uvicorn
  - pip
  - beartype
  - neo4j-python-driver
```
Which results in:

![image](https://user-images.githubusercontent.com/11840348/147776716-cba93dec-2e65-4c6b-9153-32ad6fc1d879.png)

I also tested 0.19.0 and get some linking warnings with several packages like libpng.

When I go back to 0.18.2 everything works great.  ~~I looked and 0.19.1 is maybe pre-release or something, since it's not marked as a release on the mamba repo?~~ I was looking at the wrong tag. 

Just wanted to raise this issue in case other people run into it.

Thanks for mamba and micromamba!  They are wonderful tools!

**Comment by wholtz** [comment]
Hello @stevemarin -- thank you for your interest in micromamba.

Our images are under active development and in the past month there has been some substantial changes in how activation of the conda environments is handled. In the 0.18.2 image, we were modifying the PATH to include the base environment and that is how `pip` was being found in your use case. We no longer modify the PATH. Instead, you can set the default conda environment to be active during your `RUN` command by first setting:
```Dockerfile
ARG MAMBA_DOCKERFILE_ACTIVATE=1
```
Please see the [README](https://github.com/mamba-org/micromamba-docker#running-commands-in-dockerfile-within-the-conda-environment) for more information on how to make use of conda environments within Dockerfile `RUN` commands.

**Comment by wholtz** [comment]
I also should have added, that you may want to move your `pip` installed dependencies within your yaml file -- see [conda docs](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#create-env-file-manually).

**Comment by stevemarin** [comment]
Thank you.  I checked the docs before posting, but I didn't appreciate the information in the README.  Above the relevant portion it says: ```The 'base' conda environment is automatically activated when the image is running.```  I wrongly assumed that'd be the same while executing the Dockerfile.  Thanks for pointing out my error!

**Comment by gustavorps** [comment]
```
% docker build --secret id=GITHUB_USE,env=GITHUB_USE --secret id=GITHUB_TOKEN,env=GITHUB_TOKEN -t gustavorps/ostec .
...
 => ERROR [stage-1 13/14] RUN pip install external/deep3dfacerecon/nvdiffrast                                                                                                                   0.3s
------                                                                                                                                                                                               
 > [stage-1 13/14] RUN pip install external/deep3dfacerecon/nvdiffrast:
0.261 /bin/sh: 1: pip: not found
------
Dockerfile:37
--------------------
  35 |     RUN micromamba install -n base -c conda-forge --yes python=3.6.13
  36 |     ARG MAMBA_DOCKERFILE_ACTIVATE=1
  37 | >>> RUN pip install external/deep3dfacerecon/nvdiffrast
  38 |     
  39 |     RUN micromamba install -n base --yes --file ./enviroment.yml && \
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install external/deep3dfacerecon/nvdiffrast" did not complete successfully: exit code: 127
```

```dockerfile
FROM mambaorg/micromamba:2.3.0 AS micromamba

FROM debian

USER root
WORKDIR /opt/ostec

RUN apt-get update && apt-get install -y git

# if your image defaults to a non-root user, then you may want to make the
# next 3 ARG commands match the values in your image. You can get the values
# by running: docker run --rm -it my/image id -a
ARG MAMBA_USER=mambauser
ARG MAMBA_USER_ID=57439
ARG MAMBA_USER_GID=57439
ENV MAMBA_USER=$MAMBA_USER
ENV MAMBA_ROOT_PREFIX="/opt/conda"
ENV MAMBA_EXE="/bin/micromamba"

COPY --from=micromamba "$MAMBA_EXE" "$MAMBA_EXE"
COPY --from=micromamba /usr/local/bin/_activate_current_env.sh /usr/local/bin/_activate_current_env.sh
COPY --from=micromamba /usr/local/bin/_dockerfile_shell.sh /usr/local/bin/_dockerfile_shell.sh
COPY --from=micromamba /usr/local/bin/_entrypoint.sh /usr/local/bin/_entrypoint.sh
COPY --from=micromamba /usr/local/bin/_dockerfile_initialize_user_accounts.sh /usr/local/bin/_dockerfile_initialize_user_accounts.sh
COPY --from=micromamba /usr/local/bin/_dockerfile_setup_root_prefix.sh /usr/local/bin/_dockerfile_setup_root_prefix.sh

RUN /usr/local/bin/_dockerfile_initialize_user_accounts.sh && \
    /usr/local/bin/_dockerfile_setup_root_prefix.sh
  
RUN git clone https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/gustavorps/ostec.git --recursive --depth 1 . && \
    ls -al

USER $MAMBA_USER

RUN micromamba install -n base -c conda-forge --yes python=3.6.13
ARG MAMBA_DOCKERFILE_ACTIVATE=1
RUN pip install external/deep3dfacerecon/nvdiffrast

RUN micromamba install -n base --yes --file ./enviroment.yml && \
    micromamba clean --all --yes
```

**Comment by wholtz** [comment]
@gustavorps  - you need to explictly install `pip`. It does not come automatically with python.
```
RUN micromamba install -n base -c conda-forge --yes python=3.6.13 pip
```
