### ISSUE TITLE
Issues working in docker:  ERROR   Prefix and name arguments are empty.

### ISSUE THREAD

**Issue by Casyfill** [mamba-org/micromamba-docker#12]
I am using `mambaorg/micromamba:0.8.2` to run CI using Drone.
Here is my reducted Dockerfile:
```
FROM mambaorg/micromamba:0.8.2 as base
COPY ./resources/env.yml .
RUN cat env.yml
RUN micromamba install -y -n base -f env.yml  && \
    rm /opt/conda/pkgs/cache/*
COPY ./resources/requirements.txt .
RUN pip install -r requirements.txt

FROM {registry}/research-base:base as test
COPY ./resources/test_requirements.txt .
RUN pip install -r test_requirements.txt
COPY setup.cfg .  
```
When I create the docker image and run it locally, micromamba is working and all runs smoothly. In the pipeline, however, when I run it like that:
```
- name: run tests
  image: {registry}/research-base:test
  commands:
    - which python
    - python --version
    - which micromamba
    - micromamba list
    - python -m flake8 ./SE
    - python -m pytest ./tests
```
Micromamba is seen, and python is the one installed via Yaml, BUT returns error on `mcromamba list`
```
28 | ERROR   Prefix and name arguments are empty.
```
When I removed it, it tried running tests, but cant find dependencies.
When I tried adding this command:
```
- eval "$(./bin/micromamba shell hook -s bash)"
- micromamba activate
```
it returned this:
```
10 | The following argument was not expected: activate
11 | Run with --help for more information.
```

PS: Some additional info on docker:
```

Client: Docker Engine - Community
--
6 | Version:           19.03.13
7 | API version:       1.40
8 | Go version:        go1.13.15
9 | Git commit:        4484c46
10 | Built:             Wed Sep 16 16:58:04 2020
11 | OS/Arch:           linux/amd64
12 | Experimental:      false
13 |  
14 | Server: Docker Engine - Community
15 | Engine:
16 | Version:          19.03.13
17 | API version:      1.40 (minimum version 1.12)
18 | Go version:       go1.13.15
19 | Git commit:       4484c46
20 | Built:            Wed Sep 16 17:04:43 2020
21 | OS/Arch:          linux/amd64
22 | Experimental:     false
23 | containerd:
24 | Version:          v1.3.7
25 | GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
26 | runc:
27 | Version:          1.0.0-rc10
28 | GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
29 | docker-init:
30 | Version:          0.18.0
31 | GitCommit:        fec3683
```

**Comment by wholtz** [comment]
I am not familiar with Drone CI, but I'm guessing each of those commands are passed to individual containers, such that the `micromamba list` effective does: `docker run mambaorg/micromamba micromaba list`. This results in .bashrc not being sourced. In this context, three other versions of the command that will work are:
1. `micromamba list --prefix /opt/conda` 
2. `micromamba list --name base` 
3. `/bin/bash -c "micromamba list"`

When you tried:
```
- eval "$(./bin/micromamba shell hook -s bash)"
- micromamba activate
```

You likely created two separate container instances and the second command runs independently of the first command. 

You could use:
```
/bin/bash -c 'eval "$(./bin/micromamba shell hook -s bash)" && micromamba activate'
```
But that is rather pointless, as any command running under `/bin/bash` will already have the shell hook and the base environment active, as .bashrc will have been sourced.

**Comment by Casyfill** [comment]
Thanks @wholtz . I don't think that's the case. 
After some tinkering, I completely removed any initialization and it seems to start running - although I swear I was having multiple `Prefix and name arguments are empty` before. I am sure It's that I was doing something wrong on my side, but perhaps mamba could give some more info on what is going on.

**Comment by Casyfill** [comment]
PS pulled this image again in other CI, also in drone, and again getting `ERROR   Prefix and name arguments are empty.` on `mamba list`, although packages are there.

Moreover,  I ran `mamba list` and got `pandas=1.1.5` at the end of dockerfile, but once image is pulled, I run 
`python -c "import pandas as pd;print(pd.__version__)"` and getting `1.2.3`

**Comment by wholtz** [comment]
In the micromamba image there are symlinks from conda, miniconda, and mamba to /bin/micromamba. I put them in there as a convenience for when people fall back on old habits and forget that they are currently using micromamba. However, they are confusing things a bit as evidenced by your experience. The micromamba binary does not have an activate subcommand (`micromamba activate`). When the shell hooks are installed, there is a shell function micromamba() that captures execution of `micromamba ...` (but not `/bin/micromamba ...`). If the subcommand is activate or deactivate, then shell function performs the steps necessary to activate the environment.  If the subcommand is anything else, then the subcommand gets forwarded along to the micromamba binary.

Therefore, when you run `mamba activate`, that is not going to call the micromaba() shell function and you effectively run `/bin/micromamba activate`, which results in the the error you reported.

I should probably remove the symlinks.

**Comment by Casyfill** [comment]
thanks for the detailed explanation. It all makes sense - perhaps copying
this text to the readme (and maybe highlighting “do not use micromamba
activate” ) would be sufficient ?
