### ISSUE TITLE
Run update.sh in GH Action on upstream version bump

### ISSUE THREAD

**Issue by maresb** [mamba-org/micromamba-docker#120]
As I remarked in https://github.com/mamba-org/micromamba-docker/issues/119#issuecomment-1025115603, neither tags of the form `0.20.0` nor `git-abc1234` are sufficient to uniquely specify an image. (I feel like our current recommendation of using digests is correct, but overkill.) One possible solution would be to use combined tags like `0.20.0-git-abc1234`. However that solution masks another underlying problem, namely that the current GH Action fails to run the `update.sh` script, so the readme and `ARG VERSION` have the wrong version numbers. If this were fixed, then an upstream version change would trigger a commit here, and therefore the git-style tags would become unique.

I think it's better in this case to solve the underlying problem and run `update.sh` on GH. Unfortunately this involves setting up git credentials in the Action. I'm not yet experienced enough on GH Actions to comprehend all the security implications... (I'm sure it's not _that_ hard, but it probably deserves diligence from someone with more experience than I have, since this isn't a good case for e.g. copy-pasting from a random blog. :joy:)

**Comment by wholtz** [comment]
Using digests in `FROM` lines is a docker best practice and not specific to micromamba-docker.

Getting this completely automated is a bit tricky. I believe it would involve me turning off branch-protection.

There is an easy solution with less automation:
1. Remove calls to `check_version.py` in the CI and CD workflows
2. No longer pass the `VERSION` build-args in the CD workflow
2. Remove the 6-hour schedule for running the CD workflow

A person would then have to run `update.sh` after a release, generate a PR, and get the result merged to main before dockerhub will get a new build. 

It would be easy to add back some automation to generate the PR with the `update.sh` commit when new versions of micromamba arrive on conda-forge.

**Comment by maresb** [comment]
That's a really interesting thought. Doing it manually could make a lot of sense short-term.

There's also a decent chance that in some months I'll have set up something similar for on something less critical, and may have more concrete ideas.

With your last sentence, do you mean that instead of pushing in CD we could trigger a PR à la regro/cf-autotick-bot? That would be really cool.

**Comment by wholtz** [comment]
I'm not familiar with regro/cf-autotick-bot, but here is the somewhat reduced automation I am envisioning:
1. Create a new GitHub Actions workflow 'Create_update_PR', which runs a workflow on a 6 hour schedule. It runs `check_version.py` and if a new version of micromamba is found on conda-forge, then it will:
     1. create a new branch `update_to_$VERSION` 
     2. run `update.sh`
     2. generate a commit
     3. push commit
     4. generate a PR
2. I manually merge these PRs after they pass CI.

**Comment by maresb** [comment]
Yes, that's exactly what I meant. You seem to have very nicely broken down all the individual steps.

**Comment by wholtz** [comment]
I implemented this, but GitHub Actions are currently degraded, so I can't even do the limited testing I was hoping to do. I will leave this issue open until we successfully process a micromamba release on the new configuration.

**Comment by maresb** [comment]
That's very exciting. Not that I'm very experienced, but I read through it, and it looks good to me. I'm looking forward to seeing what it does.

**Comment by maresb** [comment]
Micromamba 0.21.0 is out!
https://github.com/mamba-org/mamba/releases/tag/2022.02.07

**Comment by maresb** [comment]
Just found this in the [docs for the PR action](https://github.com/peter-evans/create-pull-request#action-behaviour):

> If a pull request already exists and there are no further changes (i.e. no diff with the current pull request branch) then the action exits silently.

So if I'm reading that correctly I think it'll be fine. Sorry for the noise!

**Comment by wholtz** [comment]
I let the cronjob kick off the initial PR generation and then manually triggered the workflow again.  The second invocation didn't leave any trace. 

But the initial PR did not automatically trigger the CI workflow. I had to disable branch protection to continue the process. This seems to happen most times that I update `.github/workflows/test.yaml` and likely it will be fine for the next PR.

**Comment by maresb** [comment]
Looks like not triggering the CI is a [known issue with various possible workarounds](https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs).

**Comment by wholtz** [comment]
The workarounds that would result in the automatically generated PR kicking off the CI workflow are all messy. So I'm going to stick with the simple but slightly less automated solution:

> Use the default GITHUB_TOKEN and allow the action to create pull requests that have no checks enabled. Manually close pull requests and immediately reopen them. This will enable on: pull_request workflows to run and be added as checks.

The workflow will be:
1. PR is automatically generated
2. I will then close the PR
3.  I will immediately re-open the PR
4. wait for CI workflow to complete
5. Click 'Merge' button

The only small downside of this is that I have to sit and wait for CI to run.
