### ISSUE TITLE
Feature Request: Enable commands via `docker exec`

### ISSUE THREAD

**Issue by bchalk101** [mamba-org/micromamba-docker#128]
Hi,

I've run into a problem where I need to be able to execute commands via `docker exec` or similar, however unless the image is entered into interactively the conda env is not activated.

Example:
`docker run -it --rm --name test -d mambaorg/micromamba`
`docker exec test micromamba install`

This results in the following:
```
info     ****************** Backtrace Start ******************
debug    Loading configuration
trace    Compute configurable 'create_base'
trace    Compute configurable 'no_env'
trace    Compute configurable 'no_rc'
trace    Compute configurable 'rc_files'
trace    Compute configurable 'root_prefix'
trace    Get RC files configuration from locations up to HomeDir
trace    Configuration not found at '/home/mambauser/.mambarc'
trace    Configuration not found at '/home/mambauser/.condarc'
trace    Configuration not found at '/home/mambauser/.conda/condarc.d'
trace    Configuration not found at '/home/mambauser/.conda/condarc'
trace    Configuration not found at '/home/mambauser/.conda/.condarc'
trace    Configuration not found at '/opt/conda/.mambarc'
trace    Configuration not found at '/opt/conda/condarc.d'
trace    Configuration not found at '/opt/conda/condarc'
trace    Configuration not found at '/opt/conda/.condarc'
trace    Configuration not found at '/var/lib/conda/.mambarc'
trace    Configuration not found at '/var/lib/conda/condarc.d/'
trace    Configuration not found at '/var/lib/conda/condarc'
trace    Configuration not found at '/var/lib/conda/.condarc'
trace    Configuration not found at '/etc/conda/.mambarc'
trace    Configuration not found at '/etc/conda/condarc.d/'
trace    Configuration not found at '/etc/conda/condarc'
trace    Configuration not found at '/etc/conda/.condarc'
trace    Update configurable 'no_env'
trace    Compute configurable 'file_specs'
trace    Compute configurable 'spec_file_env_name'
trace    Compute configurable 'env_name'
trace    Compute configurable 'envs_dirs'
trace    Compute configurable 'use_target_prefix_fallback'
trace    Compute configurable 'target_prefix'
trace    Get RC files configuration from locations up to TargetPrefix
trace    Configuration not found at '/home/mambauser/.mambarc'
trace    Configuration not found at '/home/mambauser/.condarc'
trace    Configuration not found at '/home/mambauser/.conda/condarc.d'
trace    Configuration not found at '/home/mambauser/.conda/condarc'
trace    Configuration not found at '/home/mambauser/.conda/.condarc'
trace    Configuration not found at '/opt/conda/.mambarc'
trace    Configuration not found at '/opt/conda/condarc.d'
trace    Configuration not found at '/opt/conda/condarc'
trace    Configuration not found at '/opt/conda/.condarc'
trace    Configuration not found at '/var/lib/conda/.mambarc'
trace    Configuration not found at '/var/lib/conda/condarc.d/'
trace    Configuration not found at '/var/lib/conda/condarc'
trace    Configuration not found at '/var/lib/conda/.condarc'
trace    Configuration not found at '/etc/conda/.mambarc'
trace    Configuration not found at '/etc/conda/condarc.d/'
trace    Configuration not found at '/etc/conda/condarc'
trace    Configuration not found at '/etc/conda/.condarc'
trace    Update configurable 'no_env'
trace    Compute configurable 'target_prefix_checks'
error    No target prefix specified
critical Aborting.
info     ****************** Backtrace End ********************
```

Was wondering if this could be added to the micromamba image or any ideas of how to enable it?

**Comment by wholtz** [comment]
Hello @bchalk101, thank you for your interest in micromamba.

The output from `micromamba install` is rather noisy and may have confused you. The key line of output is `error    No target prefix specified` indicating you did not supply all the required parameters.
```docker exec test micromamba install -n base -c conda-forge -y openssl```
would be the full command to install openssl into the base environment (and it works for me with mambaorg/micromamba:0.21.0). If you then want to execute a program within a conda environment via a `docker exec` command, then you can make use of a new `micromamba` feature:
```docker exec test micromamba run openssl```
or if you want to avoid the "μmamba" ascii banner, then you could do:
```docker exec test /usr/local/bin/_entrypoint.sh openssl```

With that information, are you able to do what you need?

**Comment by bchalk101** [comment]
Hi @wholtz, thank you for working on it!

So not exactly, I was wondering if it is possible in the same manner that you can run `docker run -it --rm --name test mambaorg/micromamba micromamba install python -c conda-forge` and it activates the environment and runs the install within `base`, could that be done with `docker exec`.

The specific reason is that I have a Dockerfile, which installs python and other tools into the base conda environment within the image. I want to enable users to be able to run `docker exec python <script>.py` and it uses the python from within the base environment as you would with `docker run`, without having to use additional commands such as `micromamba run` or `/usr/local/bin/_entrypoint.sh`.

**Comment by wholtz** [comment]
`docker exec` does not appear to execute `.bashrc` or `.profile` so I don't see way to implement exactly what you want. 

There are some other options that I don't consider to be "clean" as they run programs from the conda environment without activating the conda environment. By placing `python` within `$PATH` you can get the behavior you desire.  You could set `PATH` to include `/opt/conda/bin` or you can symlink `/opt/conda/bin/python` to `/usr/local/bin/python`:

```bash
docker run -it --rm --name test -d mambaorg/micromamba
docker exec test micromamba install -c conda-forge -y -n base python
docker exec -u 0:0 test ln -s /opt/conda/bin/python /usr/local/bin/python
docker exec test python --version
```

**Comment by wholtz** [comment]
Just to clarify,
```bash
docker run -it --rm --name test mambaorg/micromamba micromamba install python -c conda-forge -y -n base
```
works because `micromamba` (which is not in a conda environment) is in `/bin` which is within the default `$PATH`.

**Comment by maresb** [comment]
@bchalk101 and @wholtz, in general, one possibility to achieve activation from `docker exec` is

```bash
docker exec -it containername bash -i -c "command"
```

**Comment by wholtz** [comment]
Closing as I don't see a way to enable the requested functionality.
