### ISSUE TITLE
Additional cleanups

### ISSUE THREAD

**Issue by marscher** [mamba-org/micromamba-docker#13]
Hi there,
thanks for this great container! I'd like to mention, that cleaning via mamba after the installation saves additional memory:

``` RUN micromamba install -y -n base -f /root/env.yaml && \
    rm /opt/conda/pkgs/cache/* && \ 
    mamba clean -ay
```

Does cleaning makes the deletion of the pkgs cache optional? A high-level interface call should be preferred, right?

Eventually this should be added to the build instructions (as people tend to copy/paste/adopt things).

**Comment by wholtz** [comment]
Hi @marscher -- thanks for your interest in micromamba and for the suggestion. This is a good idea. I have updated the docs and examples.
