### ISSUE TITLE
Using bitnami/minideb as a base system

### ISSUE THREAD

**Issue by Midnighter** [mamba-org/micromamba-docker#14]
Since size is obviously a concern for this image, I was wondering whether you are interested in replacing `debian:buster-slim` with [`bitnami/minideb:buster`](https://hub.docker.com/r/bitnami/minideb) which is even smaller. I ran a quick local test replacing the `$BASE_IMAGE` and it seems to work just fine but it's hard for me to imagine all the implications.

I'm happy to create a PR if that's desired.

**Comment by wholtz** [comment]
Hi @Midnighter -- thanks for the the interest in micromamba and for posting your idea. I just did a test build with bitnami/minideb:buster and there was a 2% size reduction in the uncompressed image.  I'm concerned that the bitnami base image is less well known and the associated limitations aren't common knowledge. Therefore, I'd be open to adding this new base image under a new image tag: "$VERSION-mini" while continuing the slim builds with the tags "$VERSION-slim" and "$VERSION". 

A PR to implement these changes would need to update the GitHub Actions that build and push to dockerhub as they are not currently configured for multiple images per release. These changes to the CD system are also needed for #6, so there are broader benefits to this work.

**Comment by Midnighter** [comment]
Thanks for the reply. It seems I haven't been paying attention to latest developments of the Debian slim image. A 2% reduction doesn't at all seem worth the trouble.
