### ISSUE TITLE
Cannot install from requirements.txt

### ISSUE THREAD

**Issue by ashanbrown** [mamba-org/micromamba-docker#162]
pip installs of a requirements file appear to expect the requirements file to be in `/tmp`.  Here's a test case Dockerfile:

```
FROM mambaorg/micromamba:latest

RUN mkdir foo

RUN touch foo/requirements.txt

RUN echo $' \n\
name: test \n\
channels: \n\
  - conda-forge \n\
dependencies:\n\
  - pytest \n\
  - pip: \n\
    - -r requirements.txt' > foo/environment.yml

RUN cd foo && micromamba create -f environment.yml
EOF

```

Running this produces the output:
```
...
#8 10.17 Installing pip packages: -r requirements.txt
#8 10.60 ERROR: Could not open requirements file: [Errno 2] No such file or directory: '/tmp/requirements.txt'
#8 10.74 critical libmamba pip failed to install packages
```

Is it expected that I'd need an absolute path to the requirements file or is this a problem setting the working directory for pip?  Thanks.

**Comment by wholtz** [comment]
Hi @ashanbrown - thank you for your interest in micromamba and for reporting this problem. 

This is an issue with the micromamba binary and not a docker specific issue, so I have opened an issue with the micromamba developers: https://github.com/mamba-org/mamba/issues/1726.
