### ISSUE TITLE
Permission denied to access files in shared folder

### ISSUE THREAD

**Issue by rgaiacs** [mamba-org/micromamba-docker#195]
Consider the following minimal working example:

`Dockerfile`:

``` 
FROM mambaorg/micromamba
RUN micromamba install -y -n base -c conda-forge python=3.10 \
    && micromamba clean --all --yes
WORKDIR /tmp
CMD ls
```

`docker-compose.yml`

``` 
version: "3.9"
services:
  web:
    build: .
    command: python main.py
    ports:
      - "4444:4444"
    volumes:
      - .:/tmp
```

`main.py`

```
with open('foo.txt', 'w') as _file:
    _file.write('foo\n')
```

When I run `docker-compose up`, I get

```
Recreating tmpa4aakqmvo7_web_1 ...
Attaching to tmpa4aakqmvo7_web_1
web_1  | python: can't open file '/tmp/main.py': [Errno 13] Permission denied
```

Any help to resolve this?

Host information:

```
$ uname -a
Linux raniere 5.13.0-52-generic #59-Ubuntu SMP Wed Jun 15 20:17:13 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
$ docker --version
Docker version 20.10.12, build 20.10.12-0ubuntu2~21.10.1
$ docker-compose --version
docker-compose version 1.28.5, build c4eb3a1f
```

**Comment by wholtz** [comment]
Hello @rgaiacs . Thank you for the interest in `micromamba` and for reporting this issue.

What are the permissions on `main.py`? I was only able to reproduce your error if I did `chmod -r main.py` first.

**Comment by rgaiacs** [comment]
Hi @wholtz. Thanks very much for the help.

```
$ ls -l
-rw-rw-r-- 1 raniere raniere 147 Aug  1 14:42 docker-compose.yml
-rw-rw-r-- 1 raniere raniere 144 Aug  1 14:29 Dockerfile
-rw-rw-r-- 1 raniere raniere  61 Aug  1 14:17 main.py
$ grep raniere /etc/passwd
raniere:x:1001:1001:Raniere,,,:/home/raniere:/bin/bash
```

I checked the permission recursively:

```
$ pwd main.py 
/tmp/tmp.A4AaKqMVo7
$ ls -l / | grep tmp
drwxrwxrwt  46 root root        94208 Aug  2 09:04 tmp
$ ls -l /tmp | grep tmp.A4A
drwx------ 2 raniere raniere     4096 Aug  1 14:42 tmp.A4AaKqMVo7
```

And it looks good.

**Comment by wholtz** [comment]
Perhaps this is due to the older versions of `docker-compose` that you are running?  When I match your permissions don't get any errors, but I'm testing on:

```
$ uname -a
Darwin wholtz 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64
$ docker --version
Docker version 20.10.17, build 100c701
$ docker-compose --version
Docker Compose version v2.6.1
```

But I still think it is likely due to the file permissions. Could try doing `chmod 777 /tmp/tmp.A4AaKqMVo7`and see if that changes the output?

**Comment by rgaiacs** [comment]
@wholtz Thanks for the help. I'm running something on my machine and will take a few days for me to be able to update Docker on it.

> Could try doing `chmod 777 /tmp/tmp.A4AaKqMVo7` and see if that changes the output?

It does work but I was trying to avoid `chmod 777`.

I'm closing the issue for now.

**Comment by wholtz** [comment]
To avoid the `chmod` you could try matching the uid and gid between the host and container:

`docker-compose.yml`

```
version: "3.9"
services:
  web:
    build: .
        args:
              MAMBA_USER_ID=1001
              MAMBA_USER_GID=1001
    command: python main.py
    ports:
      - "4444:4444"
    volumes:
      - .:/tmp
  ```
