### ISSUE TITLE
'base' conda environment is NOT automatically activated

### ISSUE THREAD

**Issue by rgaiacs** [mamba-org/micromamba-docker#208]
`README`'s quick start says

> The 'base' conda environment is automatically activated when the image is running.
>
> ```
> $ docker build --quiet --tag my_app .
> sha256:b04d00cd5e7ab14f97217c24bc89f035db33a8d339bfb9857698d9390bc66cf8
> $ docker run -it --rm my_app python --version
> 3.9.1
> ```

It didn't work for me

```
$ uname -srv 
Linux 5.16.14-1-MANJARO #1 SMP PREEMPT Fri Mar 11 14:12:18 UTC 2022
$ docker inspect mambaorg/micromamba | head
[
    {
        "Id": "sha256:427a8101b7ffa7b1d91458a4ed9d525902b76a4ed0fbcc5e22d2af530dba1c29",
        "RepoTags": [
            "mambaorg/micromamba:latest"
        ],
        "RepoDigests": [
            "mambaorg/micromamba@sha256:8e6826b7efc8af8f1685ba648ecf482af6399db3370f4121e6831758fc836263"
        ],
        "Parent": "",
$ docker run -it --rm mambaorg/micromamba python --version
/usr/local/bin/_entrypoint.sh: line 24: exec: python: not found
```

Is the `README` out of date or did I misunderstood the `README`?

# Extra

I noticed this for the first time when using GitLab CI. I have a minimal working example at https://gitlab.com/raniere-phd/micromamba-docker-mwe/-/jobs/3006027743.

**Comment by wholtz** [comment]
Hi @rgaiacs.  The example in the `README.md` is supposed to show that an image *derived* from`mambaorg/micromamba`, with the `python` conda package added in, is able to run `python` from the `base` environment. The `mambaorg/micromamba` image does not come with `python`. Unlike `conda` (and `mamba`), `micromamba` does not have a `python` dependency.

**Comment by wholtz** [comment]
In PR #209, I attempted to make this more clear within the [Quick Start](https://github.com/mamba-org/micromamba-docker#quick-start) section.

**Comment by rgaiacs** [comment]
@wholtz Thanks for the clarification and valuable Docker image.
