### ISSUE TITLE
Operation not permitted error on ubuntu:22.04

### ISSUE THREAD

**Issue by emmaai** [mamba-org/micromamba-docker#211]
```
$ docker run -it mambaorg/micromamba:git-dee2e1b-jammy
terminate called after throwing an instance of 'std::system_error'
  what():  Operation not permitted
terminate called after throwing an instance of 'std::system_error'
  what():  Operation not permitted
/usr/local/bin/_activate_current_env.sh: line 35:    13 Aborted                 (core dumped) micromamba activate "${ENV_NAME}"
```
It's working fine on `focal`. Seems like the privilege issue on `jammy`.

**Comment by wholtz** [comment]
Hi @emmaai - thanks for the report. Please upgrade to the latest version of Docker and let me know if the issue still exists for you. 

Reference: https://askubuntu.com/questions/1408696/c-threads-fail-on-ubuntu-22-04

**Comment by emmaai** [comment]
> Hi @emmaai - thanks for the report. Please upgrade to the latest version of Docker and let me know if the issue still exists for you.
> 
> Reference: https://askubuntu.com/questions/1408696/c-threads-fail-on-ubuntu-22-04

Thanks a lot!  I just found out when trying to build from `ubuntu:jammy`.
