### ISSUE TITLE
libmamba Could not create proc dir: "/home/mambauser/.mamba/proc"

### ISSUE THREAD

**Issue by shughes-uk** [mamba-org/micromamba-docker#215]
Using 0.26.0 I see this when using `micromamba run`
```
libmamba Could not create proc dir: "/home/mambauser/.mamba/proc"
```

**Comment by wholtz** [comment]
Hi @shughes-uk - thank you for reporting this problem.

I am able to reproduce this on macOS without using docker:

```bash
$ ./micromamba run /bin/bash
warning  libmamba Could not create proc dir: "/Users/MyUserID/.mamba/proc"
$ 
```

Please repost to the [mamba-org/mamba repo](https://github.com/mamba-org/mamba) issue tracker, as that is where issues with the `micromamba` program are handled.
