### ISSUE TITLE
release notes link broken

### ISSUE THREAD

**Issue by kapsakcj** [mamba-org/micromamba-docker#221]
FYI the link listed in this [repo's release notes](https://github.com/mamba-org/micromamba-docker/releases) does not properly link to the `mamba` release notes page. I'm getting a page not found/404

broken link: https://github.com/mamba-org/micromamba-docker/blob/v0.27.0/github.com/mamba-org/mamba

What the link should be, I think? https://github.com/mamba-org/mamba/releases

or perhaps directly to the mamba CHANGELOG.md? https://github.com/mamba-org/mamba/blob/main/CHANGELOG.md

Love the project, love micromamba, and love that you all are maintaining it in a series of docker images. Thank you ❤️

**Comment by wholtz** [comment]
Thank you for the report! Should be fixed now.
