### ISSUE TITLE
Upgrade GitHub Actions to versions that use node 16

### ISSUE THREAD

**Issue by wholtz** [mamba-org/micromamba-docker#225]
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: excitedleigh/setup-nox, actions/checkout, docker/setup-buildx-action, docker/login-action, docker/build-push-action, docker/build-push-action, docker/build-push-action, docker/build-push-action, docker/login-action, docker/setup-buildx-action, actions/checkout

**Comment by wholtz** [comment]
I updated the actions in #241. The majority of these deprecation warnings went away, but there are still a couple remaining. We have until sometime in the summer of 2023 to finish this migration to node 16.

**Comment by wholtz** [comment]
The last of these was updated in 789307f5c173772611ce79f2595dd6335b0690be

**Comment by maresb** [comment]
You should consider using dependabot to automatically create PRs to bump the GHA versions. I could open a PR if you're interested.
