### ISSUE TITLE
Consider implementing the devcontainer "Feature" specification

### ISSUE THREAD

**Issue by maresb** [mamba-org/micromamba-docker#228]
[Features](https://containers.dev/implementors/features/) are a relatively new part of the devcontainer specification. They are completely new to me, so please forgive and correct any misconceptions I may have. I'd like to thank @eitsupi for bringing the subject to my attention and patiently answering lots of questions in [mamba-org/micromamba-devcontainer#7](https://github.com/mamba-org/micromamba-devcontainer/issues/7).

As far as I can tell, Features at the abstract level have virtually nothing to do with devcontainers in particular. Rather, they are a specification for how to add functionality (e.g. `micromamba`) to an existing image. This micromamba-docker repo effectively performs that very function for the debian/ubuntu/cuda base images, and also explains [how to accomplish this for other images](https://github.com/mamba-org/micromamba-docker#adding-micromamba-to-an-existing-docker-image).

There may be some complications which I haven't entirely thought through, but in principle, it seems like we could essentially refactor the current repo so that we define a Feature, and use those same scripts to build the current image.

Benefits:
- Makes it easy for people to add Micromamba to devcontainers
- Early adoption of open standards, and corresponding publicity
- Standardization (could slightly help to reduce some arbitrariness of certain implementation choices)
 
Would it make sense to create a branch here (or on my fork) to experiment with this idea?

(BTW, going in this direction, [mamba-org/micromamba-devcontainer](https://github.com/mamba-org/micromamba-devcontainer) may turn into a [Template](https://containers.dev/implementors/templates/).)

**Comment by wholtz** [comment]
Hi @maresb - I'm open to trying this out. Feel free to make a branch here (I gave you write access). I'm curious to see how well features work across a range of base images (different distros) and if the build tooling support multi-platform.

**Comment by wholtz** [comment]
I spent some time today messing with devcontainer features today. I have a need to add docker-in-docker functionality to debian-based image. A docker-in-docker devcontainer feature exists, so this seemed like an opportunity to learn a bit and hopefully build the image I need.

The main  thoughts that I took aways from this process are:
1. Features definitions appear to be 95% shell script and 5% json metadata. The shell few shell scripts I looked at appear to have lots of conditional logic for dealing with differences between linux distributions.
1. Testing of a Feature is likely a harder than testing a series of similarly modified base-images. The Feature can be applied  to an infinite range of base-images, but a series of images is known and finite. (Obviously, this flexibility is one of the big advantages of Features....)
1. I imagine that when you start applying more than one Feature to an image, that you can have interactions between the Features. And the behavior of an image with multiple Features applied may be dependent on the order the Features are applied. This may make for some difficult troubleshooting.
1. Overall, the idea is sound -- we've discussed multi-inheritance of docker images before, so there is certainly a need for better ways of adding functionality to containers. But I was hoping that was some neat abstraction or simplification of the problem that was going to make the complexity I've alluded to easier to deal with. Similar to how the union mount (additive) filesystem used by containers reduces the complexity of the filesystem. However, from what I've seen so far, devcontainers seems to be a bit of a brute force approach. Perhaps I'm missing something, or maybe devcontainers just need some more time to mature, or maybe this is just a hard problem and there aren't any easier ways forward.

I am aware that I sound underwhelmed by devcontainers and that is somewhat accurate. But I do believe the vision is good and that it is worth while for us to take a shot at developing a micromamba Feature.

**Comment by maresb** [comment]
Thanks a lot @wholtz for the thoughtful analysis!!! My first impressions are completely consistent with yours. It's not magic, but at least it's trying to standardize things somewhat.

**Comment by wholtz** [comment]
Hey @maresb, I'm doing some cleaning up and curious if we can close issue now that  [v1.0 of the micromamba dev-container feature](https://github.com/mamba-org/devcontainer-features/pkgs/container/devcontainer-features%2Fmicromamba) has been released?

**Comment by maresb** [comment]
Ya, thanks for the reminder!
