### ISSUE TITLE
/bin/conda and /bin/mamba missing in mambaorg/micromamba:0.14.0

### ISSUE THREAD

**Issue by jli** [mamba-org/micromamba-docker#23]
## Problem

It seems like `/bin/conda` and `/bin/mamba`, which were available in 0.13.1, are no longer present in 0.14.0?

## Steps to reproduce

```shell
$ docker run --rm -it --platform linux/amd64 mambaorg/micromamba:0.14.0
(base) root@bc1eb1302a18:/# which -a micromamba
/bin/micromamba
(base) root@bc1eb1302a18:/# which -a conda
(base) root@bc1eb1302a18:/# which -a mamba
```

I tried testing with micromamba 0.14.1, but it seems like that's not available on Docker Hub: https://hub.docker.com/r/mambaorg/micromamba/tags

**Comment by wholtz** [comment]
Hi @jli -- thanks for the interest in micromamba.

Before 0.14.0 there were symlinks from conda and mamba to micromamba within the image. Conda and mamba binaries have never been part of the micromamba image.  The symlinks were originally put in as a convenience, but they were sometimes confusing people (see https://github.com/mamba-org/micromamba-docker/issues/12#issuecomment-808843294 for an example). So I decided to remove the symlinks. Sorry if that broke something for you, but you should just be able to replace conda/mamba with micromamba and get the same functionality.

micromamba 0.14.1 hasn't made it to conda-forge yet, which is where the automated docker build downloads it from.

**Comment by jli** [comment]
@wholtz Ah, that all makes sense. Thanks!
