### ISSUE TITLE
Confusion with $HOME / tilde expansion in version 0.14.0

### ISSUE THREAD

**Issue by jli** [mamba-org/micromamba-docker#24]
# Problem

It seems like in 0.14.0, `$HOME` is set to `"/home/micromamba"`, while still using the default `root` user to execute the Dockerfile. This results in confusing behavior, where tilde expansion does not match the actual user running the Dockerfile.

(I ran into this because I need to set `~/.ssh/known_hosts`, so that I can `pip install` a library from Github.)

# Reproduction

```shell
% docker run --rm -it --platform linux/amd64 mambaorg/micromamba:0.14.0
(base) root@23e0e1238de6:/# whoami
root
(base) root@23e0e1238de6:/# echo $HOME
/home/micromamba
(base) root@23e0e1238de6:/# cd ~
(base) root@23e0e1238de6:~# pwd
/home/micromamba
```

On 0.13.1, `$HOME` and `~` both map to `/root`, which is what I would expect.

# Details / discussion

- Seems like this was changed in this commit: https://github.com/mamba-org/micromamba-docker/commit/dc4bf68302b2f19e80133c7ce0ff2417c09987be
- I'm not sure about the intention of the above commit, but I think it's preferable to not set the `$HOME` environment variable in the micromamba Dockerfile?
- Tangent: it seems like the `ARG VERSION=0.13.1` is out of date? Latest commit is: https://github.com/mamba-org/micromamba-docker/blob/5a3e6ad7c4f4ed795c88d2c67b0b9095d869485c/Dockerfile#L6

**Comment by wholtz** [comment]
In 954f510c4f4a51ef4ce3502fac155938a541b1ad I moved some setup code from a RUN command into a new entrypoint script. $HOME and ~ now will either be /root or /home/micromamba depending on if you run as root or non-root user.

If you want to test it out, you'll need to build the image yourself, as this won't make it to dockerhub until a new version of mamba is released.

`ARG VERSION=...` is mostly a placeholder. The [build script](https://github.com/mamba-org/micromamba-docker/blob/main/.github/workflows/push_latest.yml) supplies the current micromamba version.

Please let me know if this doesn't fully address your issue.

**Comment by wholtz** [comment]
@jli - the image mambaorg/micromamba:0.15.0 on dockerhub has the changes I implemented for this issue. Please take a look and let me know what you think.

**Comment by jli** [comment]
@wholtz Thanks! Will try it out sometime next week.

**Comment by wholtz** [comment]
Closing as I believe the issue has been resolved.
