### ISSUE TITLE
Use numeric versioning for Ubuntu images?

### ISSUE THREAD

**Issue by jonashaag** [mamba-org/micromamba-docker#249]
The non-micromamba Ubuntu 22.04 image is `ubuntu:22.04`. The micromamba Ubuntu 22.04 image is `jammy`. How about we add an additional tag `ubuntu-22.04` or similar?

**Comment by wholtz** [comment]
Yes. I can also add numeric version for the Debian images.  It will require some new code in the CD pipeline, so I'm not sure how quickly I'll get this done.

**Comment by wholtz** [comment]
This is done in fda4370c047207032fb4db9020ebb1a993bdeacb. The images with the new tags are not yet populating the container repositories, but should be shortly once I fix a bit of the CD pipeline. See https://github.com/mamba-org/micromamba-docker/issues/526
