### ISSUE TITLE
Unable to install python packages with pip inside docker container

### ISSUE THREAD

**Issue by KaIsa9** [mamba-org/micromamba-docker#267]
Micromamba fails while trying to install package with **pip** inside docker container with the message: 
"#6 24.33 error    libmamba Subprocess call failed: Invalid argument
#6 24.33 info     libmamba Freeing transaction.
#6 24.33 info     libmamba Freeing solver.
#6 24.33 info     libmamba Freeing pool.
#6 24.33 critical libmamba Subprocess call failed. Aborting. 

Docker version 23.0.1, build a5ee5b1dfc
micromamba:1.3.1

Dockerfiles and logs: https://gist.github.com/KaIsa9/51096040e528551e527dfd8c73c00974

**Comment by maresb** [comment]
Could you please try following these instructions?

https://github.com/mamba-org/micromamba-docker#adding-micromamba-to-an-existing-docker-image

**Comment by maresb** [comment]
Strange, this builds for me. Are you on a Mac M1 or M2?

**Comment by maresb** [comment]
Thanks for the minimal example, it makes the situation much more clear.

**Comment by irublev** [comment]
> Strange, this builds for me. Are you on a Mac M1 or M2?

No, AMD64, Manjaro Linux

**Comment by irublev** [comment]
it is crucial to have exactly to have the latest version of docker-ce. For previous versions all was absolutely ok.

**Comment by maresb** [comment]
Ah, that must be my problem! Thanks.

I don't know that this will help, but best practice dictates that one should explicitly add `pip` as a dependency whenever one includes a `pip:` dict. It looks funny, but you should use

```yaml
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
    - flakon
```

**Comment by irublev** [comment]
No, unfortunately for
```
FROM mambaorg/micromamba:1.3.1

RUN echo $'\
channels:\n\
  - conda-forge\n\
dependencies:\n\
  - python=3.8\n\
  - pip\n\
  - pip:\n\
    - flakon' >> /tmp/python_requirements.yml && \
    micromamba install -y -n base -c conda-forge python=3.8

RUN micromamba install -n base --ssl-verify false -y -f /tmp/python_requirements.yml -vvv --log-level 0 \
    && micromamba clean -ay \
```
it gives the same result:
```
 > [3/3] RUN micromamba install -n base --ssl-verify false -y -f /tmp/python_requirements.yml -vvv --log-level 0     && micromamba clean -ay:
#6 0.990 debug    libmamba Unlocking '/opt/conda/conda-meta'
#6 0.990 trace    libmamba Removing file '/opt/conda/conda-meta/conda-meta.lock'
#6 0.992 
#6 0.992 Installing pip packages: flakon
#6 0.992 info     libmamba Calling: /opt/conda/bin/python -m pip install -r /tmp/mambaf7ojJuv7Hgc --no-input
#6 0.996 error    libmamba Subprocess call failed: Invalid argument
#6 0.997 info     libmamba Freeing transaction.
#6 0.997 info     libmamba Freeing solver.
#6 1.007 info     libmamba Freeing pool.
#6 1.009 critical libmamba Subprocess call failed. Aborting.
------
Dockerfile2:13
--------------------
  12 |     
  13 | >>> RUN micromamba install -n base --ssl-verify false -y -f /tmp/python_requirements.yml -vvv --log-level 0 \
  14 | >>>     && micromamba clean -ay \
  15 |     
--------------------
ERROR: failed to solve: process "/usr/local/bin/_dockerfile_shell.sh micromamba install -n base --ssl-verify false -y -f /tmp/python_requirements.yml -vvv --log-level 0     && micromamba clean -ay" did not complete successfully: exit code: 1
```

**Comment by maresb** [comment]
What happens if you run a fresh `micromamba:1.3.1` container with a terminal and execute

```bash
micromamba install -y -n base -c conda-forge python=3.8 pip
pip install flakon
```

**Comment by irublev** [comment]
> What happens if you run a fresh `micromamba:1.3.1` container with a terminal and execute
> 
> ```shell
> micromamba install -y -n base -c conda-forge python=3.8 pip
> pip install flakon
> ```

Yes, this works as expected: https://gist.github.com/irublev/e3b0a7158dd3685364b701fab6d69474

Besides, as I already said, if we create a file /tmp/conda_requirements.yml:
```
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
```
and /tmp/pip_requirements.txt:
```
flakon
```
then the commands
```
micromamba install -f /tmp/conda_requirements.yml
pip install -r /tmp/pip_requirements.yml
```
run successfully. 

The problem is to try to install everything from a single requirements.yml file. And namely in pip dependencies.

**Comment by maresb** [comment]
I see. I agree that it is very annoying how temporary directories like this are deleted, preventing inspection. It would be so helpful if there were an environment variable to disable this behavior!

I wonder if you can still capture its output before its deleted. Here's what I'd try:
* Open a terminal in the container where you are prepared to execute `micromamba install -n base --ssl-verify false -y -f /tmp/python_requirements.yml`
* Use `docker exec` to open a second shell, and prepare a glob pattern which will allow you to inspect the file, like `cat /tmp/mamba*`
* Run `micromamba install` and then run the second command while `pip` is running.

**Comment by wholtz** [comment]
I have built the following Dockerfile with docker v23.0.1 (exact same build as referenced above) under Debian 11 and I cannot reproduce the reported error. The build completes successfully.

> ```
> FROM mambaorg/micromamba:1.3.1
> 
> RUN echo $'\
> channels:\n\
>   - conda-forge\n\
> dependencies:\n\
>   - python=3.8\n\
>   - pip\n\
>   - pip:\n\
>     - flakon' >> /tmp/python_requirements.yml && \
>     micromamba install -y -n base -c conda-forge python=3.8
> 
> RUN micromamba install -n base --ssl-verify false -y -f /tmp/python_requirements.yml -vvv --log-level 0 \
>     && micromamba clean -ay \
> ```

**Comment by wholtz** [comment]
@irublev What previous versions of docker-ce were able to complete the build for you?

**Comment by irublev** [comment]
> @irublev What previous versions of docker-ce were able to complete the build for you?

@wholtz Hi! I've downgraded right now my docker to 20.10.23:
```
❯ docker version
Client:
 Version:           20.10.23
 API version:       1.41
 Go version:        go1.19.5
 Git commit:        715524332f
 Built:             Sat Jan 21 15:13:25 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.23
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       6051f14291
  Built:            Sat Jan 21 15:12:19 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.16
  GitCommit:        31aa4358a36870b21a992d3ad2bef29e1d693bec.m
 runc:
  Version:          1.1.4
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
(via [downgrade](https://wiki.manjaro.org/index.php/Downgrading_packages) and restarting of docker service, without the latter the version of server engine remained the same as well as the error).

After this an image for exactly the same Dockerfile above was built smoothly without slightest problems, here are logs: https://gist.github.com/irublev/a347e00fc7f806d14b80849a37e7c59b

**Comment by irublev** [comment]
@maresb I've managed to print the contents of temporary files, all is ok with them. In fact, there are two of them, here are screenshots:
![image](https://user-images.githubusercontent.com/4992575/221977891-debdb0ce-50b2-46f4-b9f7-289d6c44809f.png)
![image](https://user-images.githubusercontent.com/4992575/221977972-34753d8e-1bae-4ece-a54a-730a36b23c7a.png)

I do not know what is the matter. The only thing I know is that for docker 20.10.23 all is perfect, but for docker 23.0.1 I obtain the above error...

**Comment by maresb** [comment]
That is very strange. "Invalid argument". I don't have any more ideas at this time.

**Comment by irublev** [comment]
@maresb @wholtz It is very strange, but I've found a solution to build images successfully as well as to execute `micromamba install` also successfully exactly for Docker 23.0.1. The way is to point something like `--ulimit nofile=65536:65536` as below:

```
docker build --ulimit nofile=65536:65536 --file Dockerfile2 .
```
```
docker run --ulimit nofile -it ... /bin/bash
micromamba install ...
```
Without pointing this option above commands fail as before. I have no clear explanation for that, but it is clear that this is somehow connected to the number of simultaneously opened files. Possibly if `--ulimit nofile` is not given, it is taken from Linux and, hence, we have different behavior on different OS.

**Comment by wholtz** [comment]
https://github.com/moby/moby/issues/45060

**Comment by lmeyerov** [comment]
`--ulimit...` on `docker build` is not solving for us, not sure this issue is truly closed

* works: Docker version 23.0.1, build a5ee5b1
* fails: Docker version 20.10.17, build 100c701

**Comment by wholtz** [comment]
@lmeyerov can you please open a new issue with the the details of your problem? It would be appreciated if you can post a minimal reproduction of your problem in the new issue.
