### ISSUE TITLE
RISC-V images

### ISSUE THREAD

**Issue by wholtz** [mamba-org/micromamba-docker#268]
micromamba is now building for linux/riscv64. Currently none of our base images are built for this platform. But there are pre-release builds of Debian (12) bookworm for riscv64. When Debian bookworm launches (mid-2023), we can add the riscv64 images.

https://github.com/mamba-org/mamba/pull/2329

**Comment by wholtz** [comment]
`debian:bookworm` is out, but now I'm not seeing `linux/riscv64` builds on Dockerhub....

**Comment by ifsheldon** [comment]
You can take a look at this? https://hub.docker.com/u/riscv64

**Comment by wholtz** [comment]
Interesting. I wonder why they tag the images differently than the supported Debian images.

I don't see a clean way to make use of these images without a bunch of work to keep any `mambaorg/micromaba` riscv64 image tags aligned with the platforms we currently offer.
