### ISSUE TITLE
Insufficient memory leads to package install failure, but the build still succeeds

### ISSUE THREAD

**Issue by jli** [mamba-org/micromamba-docker#29]
## Issue

I am using micromamba with a large set of both conda and pip dependencies. When running `docker build`, the `micromamba install` step fails to install some dependencies, but the `docker build` continues without error, leading to an image missing a number of dependencies.

I'm using Docker Desktop on Mac, and I noticed that increasing the memory resources for Docker from the default of 2.0GB up to 2.5GB results in successful build, so it seems like insufficient memory is causing the `micromamba install` failure.

## Desired behavior

The main issue is that the `docker build` completes successfully even though micromamba failed to install all the packages, resulting in a broken image. Ideally, micromamba would cause the build to fail.

## Details

My dockerfile:

```Dockerfile
# syntax=docker/dockerfile:1
FROM --platform=linux/amd64 mambaorg/micromamba:0.13.1
COPY environment-lock.yml /environment-lock.yml
RUN --mount=type=cache,target=/opt/conda/pkgs --mount=type=cache,target=/root/.cache \
    micromamba install -y --file /environment-lock.yml
```

The environment-lock.yml is very large, and includes both conda and pip dependencies. I tried paring it down, but it was hard to reproduce the failure with a more minimal list. Let me know if you want me to share the full list.

## Error

With `--progress plain`, I see the following output from `docker build` while micromamba is in the middle of installing pip dependencies specified in environment-lock.yml (this is after the conda deps were installed):

```
[...]
#9 441.2 Collecting tensorboard-plugin-wit==1.8.0
#9 441.2   Downloading tensorboard_plugin_wit-1.8.0-py3-none-any.whl (781 kB)
#9 442.7 Collecting tensorflow==2.5.0
#9 442.7   Downloading tensorflow-2.5.0-cp38-cp38-manylinux2010_x86_64.whl (454.4 MB)
#9 466.3 /tmp/mambafVPPFiskWCz: line 4:  2363 Killed                  /opt/conda/bin/pip install absl-py==0.11.0 apache-beam==2.30.0 [...a bunch of other pip packages...] xarray==0.16.2 --no-input
#9 DONE 466.7s
```

With some random poking, I found an example /tmp/mamba* file that looked like this:

```shell
lib/python3.8/site-packages/ansiwrap/__init__.py
lib/python3.8/site-packages/ansiwrap/ansistate.py
lib/python3.8/site-packages/ansiwrap/core.py
eval "$('/bin/micromamba' 'shell' 'hook' '-s' 'bash' '-p' '/opt/conda')"
```

## Solution(?)

It seems like the "Line 4:  ... Killed" is referring to the final line in the script mentioned above. I think the problem is that the system is terminating the command on line 4 due to running out of memory, but this failure isn't propagated to the `RUN micromamba install ...`, so the `docker build` succeeds.

I think including `set -e` or using `exec` in this script would cause the error to propagate to micromamba.

## Misc

Some instances of people saying they needed to increase the memory limits for docker build:
- https://github.com/commercialhaskell/stack/issues/3963
- https://stackoverflow.com/questions/26913110/allow-more-memory-when-docker-build-a-dockerfile

**Comment by wholtz** [comment]
Hi @jli  - thanks for the detailed report. 

I am not able to come up with any way to mitigate this at the docker-level other than giving more memory to docker, which doesn't solve the root issue.  I think this issue should be moved to https://github.com/mamba-org/mamba, which is responsible for the micromamba codebase.

I did do some work reproducing this. I wanted to avoid the complexities of the `docker build ...` environment but I needed a way to limit the memory and `ulimit` wasn't working. I ended up running micromamba in a container so I could use docker's resource limiters.

```
$ cat pip.yaml 
name: base
channels:
  - conda-forge
dependencies:
  - pip
  - pip:
    - tensorflow
$ docker run -it --rm --memory=300m --memory-swap=300m --mount type=bind,source=$(pwd),target=/mnt mambaorg/micromamba:latest micromamba install -y -vvvv -f /mnt/pip.yaml

##### MUCH OUTPUT REMOVED ######

TRACE   hard-linked '/opt/conda/pkgs/wheel-0.36.2-pyhd3deb0d_0/site-packages/wheel/wheelfile.py'
         --> '/opt/conda/lib/python3.9/site-packages/wheel/wheelfile.py'
DEBUG   23 files linked
INFO    Compiling "lib/python3.9/site-packages/wheel/__pycache__/__init__.cpython-39.pyc"
INFO    Compiling "lib/python3.9/site-packages/wheel/__pycache__/__main__.cpython-39.pyc"
INFO    Compiling "lib/python3.9/site-packages/wheel/__pycache__/bdist_wheel.cpython-39.pyc"
INFO    Compiling "lib/python3.9/site-packages/wheel/cli/__pycache__/__init__.cpython-39.pyc"
INFO    Compiling "lib/python3.9/site-packages/wheel/cli/__pycache__/convert.cpython-39.pyc"
INFO    Compiling "lib/python3.9/site-packages/wheel/cli/__pycache__/pack.cpython-39.pyc"
INFO    Compiling "lib/python3.9/site-packages/wheel/cli/__pycache__/unpack.cpython-39.pyc"
INFO    Compiling "lib/python3.9/site-packages/wheel/__pycache__/macosx_libfile.cpython-39.pyc"
INFO    Compiling "lib/python3.9/site-packages/wheel/__pycache__/metadata.cpython-39.pyc"
INFO    Compiling "lib/python3.9/site-packages/wheel/__pycache__/pkginfo.cpython-39.pyc"
INFO    Compiling "lib/python3.9/site-packages/wheel/__pycache__/util.cpython-39.pyc"
INFO    Compiling "lib/python3.9/site-packages/wheel/vendored/__pycache__/__init__.cpython-39.pyc"
INFO    Compiling "lib/python3.9/site-packages/wheel/vendored/packaging/__pycache__/__init__.cpython-39.pyc"
INFO    Compiling "lib/python3.9/site-packages/wheel/vendored/packaging/__pycache__/_typing.cpython-39.pyc"
INFO    Compiling "lib/python3.9/site-packages/wheel/vendored/packaging/__pycache__/tags.cpython-39.pyc"
INFO    Compiling "lib/python3.9/site-packages/wheel/__pycache__/wheelfile.cpython-39.pyc"
INFO    Running wrapped python compilation command /opt/conda/bin/python3.9 -Wi -m compileall -q -l -i /tmp/mambafTl74sI4Jss -j0
INFO    noarch pyc compilation failed (cross-compiling?). Success
INFO    /tmp/mambafJxKSiatqAG: line 43: : command not found
        
TRACE   entry point path: "bin/wheel"
        
DEBUG   post-link script for 'wheel' does not exist ('/opt/conda/bin/.wheel-post-link.sh')
DEBUG   Finalizing linking
TRACE   Adding package to prefix metadata at '/opt/conda/conda-meta/wheel-0.36.2-pyhd3deb0d_0.json'
Transaction finished
INFO    Opening history file: "/opt/conda/conda-meta/history"

Installing pip packages: tensorflow
INFO    Calling: /opt/conda/bin/pip install -r /tmp/mambafvJT15WettK --no-input
/tmp/mambaf8guFlIGAYT: line 43: : command not found
Collecting tensorflow
  Downloading tensorflow-2.5.0-cp39-cp39-manylinux2010_x86_64.whl (454.4 MB)
     |██████████▍                     | 147.2 MB 220 bytes/s eta 16 days, 2:11:32/tmp/mambaf8guFlIGAYT: line 4:    57 Killed                  /opt/conda/bin/pip install -r /tmp/mambafvJT15WettK --no-input
INFO    Freeing transaction.
INFO    Freeing solver.
INFO    Freeing pool.
$ echo $?
0
$
```

I believe your issue would be solved if that test case returned a non-0 exit code. And it also would seem to me that the expected behavior is that `micromamba install ...` commands that don't complete their install should return a non-0 exit code.

**Comment by jli** [comment]
Ah, I was looking for a "micromamba" repo and failed to find it, so defaulted to reporting here. I'll report over on the mamba repo, thanks! Also nice finding a simple test case :)

**Comment by jli** [comment]
I filed the issue w/ mamba-org/mamba: https://github.com/mamba-org/mamba/issues/1100

Thanks!
