### ISSUE TITLE
Use higher value for `mambauser` UID/GID 

### ISSUE THREAD

**Issue by wholtz** [mamba-org/micromamba-docker#295]
Ubuntu added a new account to the lunar release and it has UID 1000. We currently use UID 1000 for `mambauser`.  With our current Dockerfile, the build of with `ubuntu:lunar` as the base image fails.

Some possible ways forward:

1. Wait until `micromamba` v1.5.0 is released and at that time move `mambauser` to UID 10000 and add in `ubuntu:lunar` as a base image.
2. Add conditional logic to setting `MAMBA_USER_ID` such that it remains at 1000 for existing base images and is 10000 for `ubuntu:lunar` based images.

**Comment by maresb** [comment]
Perhaps we could do both: add conditional logic for `ubuntu:lunar` now and then change the default to `10000:10000` on the next minor release?

**Comment by wholtz** [comment]
Done in #344 #345 using conditional logic for lunar. I decided to use 57439 for the new uid/gid instead of 10000 in order to reduce the likelihood that we end up with another uid collision in the future. When micromamba v1.5.0 releases, I'd still like to get all our images using the the same UID and GID for `mambauser`. I will work on getting this change on the `dev` branch so it is ready to go.

**Comment by maresb** [comment]
Sounds great! Although 57439 is perhaps a bit extreme. I wonder if we should set environment variables so people writing Dockefiles don't have to remember.

**Comment by luabida** [comment]
I'm also facing this issue. I'm not sure if it's a Kubuntu standard, but my user also has 1000:1000 uid and gid. For now I'm changing my id, but it may turn to be an issue to more users in the future.

**Comment by wholtz** [comment]
@luabida - can you please tell me more about what you are doing when you run into this conflict.  Are you using our Dockerfile to add micromamba to a kubuntu image? Or are you directly making use of one of our published images?

**Comment by luabida** [comment]
@wholtz of course, here is the [Dockerfile](https://github.com/Mosqlimate-project/Data-platform/pull/34/files#diff-37487117ac7b3cef1e2b0de902970876a28d1e957c0cc2d5b6a725d89631faae). I'm using the [rootless](https://docs.docker.com/engine/security/rootless/) container approach to create the container user

**Comment by maresb** [comment]
@wholtz, is this happening now that 1.5.0 is out?

**Comment by wholtz** [comment]
Done in 8491dcc3da295754f5f085b36194638971e3f5c0
