### ISSUE TITLE
Support run init script in lexicographic order

### ISSUE THREAD

**Issue by unkcpz** [mamba-org/micromamba-docker#298]
Dear developers, 

Thanks a lot for such neat and powerful images.

We want to replace our original base image with micromamba, but I find it lacks one functionality we used, the image [phusion/baseimage](https://github.com/phusion/baseimage-docker) support having init scripts copy to a folder `init.d` with the order defined by the prefix number of script and run by lexicographic from entrypoint `my_init`. The same concept is used by the `https://github.com/jupyter/docker-stacks` with "before-notebook.d". 

Is this image supported? If this feature is welcome to be added, I am happy work on it. https://github.com/phusion/baseimage-docker/blob/master/image/bin/my_init can be reference and adopted by combining with `entrypoint.sh`.

**Comment by maresb** [comment]
Sounds to me like an excellent idea! Do you agree @wholtz?

**Comment by maresb** [comment]
We do have to be a little bit careful though... init scripts come in (at least) two different flavors... those which should run on once on container start, and those which should run on shell start. We should definitely distinguish between the two. And unfortunately due to a combination of the way Docker works and Bash idiosyncrasies, running shell startup scripts can be really flaky.

As a (mostly former) docker-stacks contributor, I can lovingly say that the startup machinery is not necessarily done in the ideal way. The project is rather old, so it's difficult to make radical changes which would lead to mass breakage. On a PR we may want to request a review from them from this perspective.

My point is that it's probably worthwhile putting in some serious thought to make sure we implement this feature correctly.

**Comment by wholtz** [comment]
I would be happy to consider a PR that adds simple init scripts as part of the entrypoint. As @maresb said, adding to the shell initialization is more complex and therefore we might want to limit this to just container startup scripts. Would running init scripts from the entrypoint cover your needs @unkcpz ?

**Comment by maresb** [comment]
I just noticed that the reference is a Python script. This Docker image is minimal and doesn't include Python, so probably you'll need to implement your scripts in Bash.

**Comment by unkcpz** [comment]
> This Docker image is minimal and doesn't include Python, so probably you'll need to implement your scripts in Bash.

This is a good point and seems a bit more complex.

> Would running init scripts from the entrypoint cover your needs @unkcpz ?

This is what I tried for the image I prepared, and it indeed cover my use case so I'd not go into having the feature implemented. 

However, I encountered an issue that block me for using this base image and I think it is related and can be potentially solved with a proper init script. I use `micromamba run -n <core-services> pg_ctl --timeout=180 -w -D /home/${SYSTEM_USER}/.postgresql -l /home/${SYSTEM_USER}/.postgresql/logfile start` as on of startup scripts in `_init.sh`. It runs and start but not properly give control back to shell. I can not even `ctrl+c` to close the container. The same problem happened to the rabbitmq start-up script in `_init.sh`. 
Do I misuse some of the functionalities of this base image? Let me know if it is better to be having an dedicated issue for it. 

[This](https://github.com/unkcpz/aiida-core/blob/docker-stack/.docker/stack/base-with-services/_init.sh) is how I run start up script to launch services. And [here](https://github.com/unkcpz/aiida-core/tree/docker-stack/.docker/stack/base-with-services/init.d) are four start up scripts.

Thanks in advanced.

**Comment by maresb** [comment]
Hi @unkcpz, I am wondering what is your motivation for installing everything into a single image? I would rather use separate containers for separate services. I see that you already have a [docker-compose.yml](https://github.com/unkcpz/aiida-core/blob/docker-stack/.docker/docker-compose.yml) which looks very promising.

In my experience, conda-forge is not so great for services. (Instead I use conda-forge for installing and developing applications and libraries which have complex and/or non-Python dependencies.) Services tend to pin dependencies fairly strictly, and thus having multiple services in a single Conda environment quickly leads to dependency conflicts. But if you're working with a single service, then usually there's a Docker container which is better maintained than the Conda recipe.

**Comment by unkcpz** [comment]
Hi @maresb, the reasons are 1) the backward compatibility where we used this image for our tutorial and some users are using it. 2) We use the image for the jupyterhub server we deployed, through Z2JH recipe, the architecture needs to be adopted if the services are not in the image. 
We plan to provide two ways using the same base image to make everything easy to maintain. 
I find micromamba stack is general good since it is easy for system user name change compared to jupyter-docker-stack we used, it is easy to manage the packages. 
The service start is the only issue I have to make it work, so if you can tell me how to workaround it, I can continue on adopt it for our use case.

**Comment by unkcpz** [comment]
Okay, thanks! I'll take a look at that. I close this issue for the moment.
