### ISSUE TITLE
Files get copied as root, cannot chown/chmod after copy

### ISSUE THREAD

**Issue by nstrelow** [mamba-org/micromamba-docker#31]
Version: 0.15.2

Since the user is `micromamba`, but the default user executing COPY/ADD in Docker is `root`, files that get copied over cannot be changed or modified by user `micromamba`.

Failing example:
```Dockerfile
ADD script.sh /home/micromamba/script.sh
RUN chmod +x /home/micromamba/script.sh
```
Error: ` changing permissions of '/home/micromamba/script.sh': Operation not permitted`
Explanation: `script.sh` is owned by `root`, user `micromamba` cannot change `root` files.

The problem and a solution is detailed here: https://github.com/moby/moby/issues/6119#issuecomment-338920866
### Solution
```Dockerfile
ADD --chown=micromamba:micromamba script.sh /home/micromamba/script.sh
```

I am leaving this here for others to see, took me a while to figure out.

It might be good to add `env.yaml` using chown, so users of this image have a example to go with.

**Comment by wholtz** [comment]
Hi @nstrelow - thank you for your interest in micromamba-docker. I have updated the examples to use `COPY --chown=micromamba:micromamba ...` in 1ec7754eb1e9c606bc1a3bc263c1eea84ae6451b as COPY is preferred over ADD ([Dockerfile best practices](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#add-or-copy)).

**Comment by nstrelow** [comment]
Good to know the COPY thing, always wondered what was better ^^
