### ISSUE TITLE
Configuration file specified but does not exist

### ISSUE THREAD

**Issue by calvinp0** [mamba-org/micromamba-docker#315]
A couple of days ago, the docker image I had created based off the micromamba-docker has begun to fail at building. More accurately put, when I am using Julia provided by conda-forge, and then in the Julia REPL I execute the following `'Using Pkg; Pkg.add("PyCall"); Pkg.build("PyCall")'`

This command execution used to work fine, but now returns the following error:

```
#15 29.18 ERROR: LoadError: Error building `PyCall`:
#15 30.12 Collecting package metadata (current_repodata.json): ...working... failed
#15 30.12
#15 30.12 InvalidVersionSpec: Invalid version '>=': invalid operator
#15 30.12
#15 30.12 [ Info: Running `conda install -y numpy` in root environment
#15 30.12 ERROR: LoadError: failed process: Process(setenv(`/opt/conda/bin/conda install -y numpy`,["_CE_M=", "PWD=/home/mambauser/Code/RMG-Py", "PATH=/opt/conda/envs/rmg_env/bin:/opt/conda/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", "JULIA_LOAD_PATH_BACKUP=", "JULIA_CONDAPKG_EXE=/opt/conda/bin/conda", "JULIA_PROJECT_BACKUP=", "LC_ALL=C.UTF-8", "JULIA_DEPOT_PATH_BACKUP=", "MAMBA_USER=mambauser", "ENV_NAME=rmg_env"  …  "JULIA_CONDAPKG_BACKEND=System", "JULIA_LOAD_PATH=@:/tmp/jl_ujSQJQ", "_=/opt/conda/envs/rmg_env/bin/python", "_CE_CONDA=", "MAMBA_ROOT_PREFIX=/opt/conda", "JULIA_CONDAPKG_BACKEND_BACKUP=", "HOME=/root", "JULIA_DEPOT_PATH=/opt/conda/envs/rmg_env/share/julia:", "PYTHONIOENCODING=UTF-8", "JULIA_SSL_CA_ROOTS_PATH=/opt/conda/envs/rmg_env/ssl/cacert.pem"]), ProcessExited(1)) [1]
```

Now I realise that this may be an issue with the package PyCall itself, but I did raise an issue with them, as seen [here](https://github.com/JuliaPy/PyCall.jl/issues/1038), but the developer asserts that it is the conda installation that is broken.

Here is my Dockerfile

```dockerfile
# bring in the micromamba image
FROM mambaorg/micromamba:jammy


USER root

# Install and update APT; git cmake and build-essential are required for
RUN apt-get update && apt-get install -y \
    git \
    gcc \
    g++ \
    make \
    libgomp1\
    libxrender1 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set env variables
ARG MAMBA_USER=mambauser
ENV MAMBA_ROOT_PREFIX="/opt/conda"
ENV MAMBA_EXE="/bin/micromamba"

# Create a directory
RUN mkdir -p /home/$MAMBA_USER/Code
WORKDIR /home/$MAMBA_USER/Code

# Git clone the repo
RUN git clone https://github.com/ReactionMechanismGenerator/RMG-Py.git
RUN git clone https://github.com/ReactionMechanismGenerator/RMG-database.git

# Install base conda environment
RUN micromamba install -n base -c conda-forge --yes python=3.10 mamba \ 
    && micromamba clean --all --yes

# Install RMG-Py
WORKDIR /home/$MAMBA_USER/Code/RMG-Py
RUN micromamba env create -f environment.yml -n rmg_env -y \
    && micromamba clean --all --yes
ARG MAMBA_DOCKERFILE_ACTIVATE=1
ENV ENV_NAME=rmg_env
# Compile RMG-Py
RUN make

# Link Julia and python
RUN julia -e 'using Pkg; Pkg.add("Conda"); Pkg.build("Conda");Pkg.add(PackageSpec(name="PyCall", rev="master")); Pkg.build("PyCall"); Pkg.add(PackageSpec(name="ReactionMechanismGenerator", rev="main"))' |
RUN python -c "import julia; julia.install(); import diffeqpy; diffeqpy.install()" 

SHELL [ "/bin/bash", "-c" ]
```

I am at a loss at what has changed. You may wonder why I install `mamba` in the base environment. Well, if I didn't do that, the in Julia, the package `Conda` would result in an error saying that it cannot find the environment variable for `"CONDA_JL_CONDA_EXE"`. I only started installing `mamba` in the base in order to see if it would fix the issue. If I did point that environment variable to `/usr/bin/micromamba`, the package would build but then `PyCall` would result in another error saying it cannot find the configuration file `condarc-jl.yml`

Edit:
To provide further detail on pointing the env variable to `/usr/bin/micromamba`, I get this error:

```julia
julia> Conda.add("numpy")
[ Info: Running `conda install -y numpy` in root environment
info     libmamba ****************** Backtrace Start ******************
debug    libmamba Loading configuration
trace    libmamba Compute configurable 'create_base'
trace    libmamba Compute configurable 'no_env'
trace    libmamba Compute configurable 'no_rc'
trace    libmamba Compute configurable 'rc_files'
error    libmamba Configuration file specified but does not exist at '/home/calvin/micromamba/envs/rmg_env/condarc-julia.yml'
critical libmamba Aborting.
info     libmamba ****************** Backtrace End ********************
ERROR: failed process: Process(setenv(`/home/calvin/bin/micromamba install -y numpy`,["_CE_M=", "PATH=/home/calvin/micromamba/envs/rmg_env/bin:/home/calvin/mambaforge/condabin:/home/calvin/.local/bin:/home/calvin/Downloads/hadolint-Linux-x86_64:/home/calvin/julia/bin:/home/calvin/mambaforge/envs/t3_env/bin:/home/calvin/mambaforge/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/calvin/Code/RMG-Py", "QT_ACCESSIBILITY=1", "DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus", "STARSHIP_SESSION_KEY=2655225532155272", "XDG_SESSION_DESKTOP=ubuntu", "JULIA_CONDAPKG_EXE_BACKUP=", "XDG_SESSION_TYPE=x11", "SYSTEMD_EXEC_PID=4712", "arc_path=/home/calvin/Code/ARC/"  …  "XDG_SESSION_CLASS=user", "DISPLAY=:1", "LANGUAGE=en_IL:en", "MAMBA_EXE=/home/calvin/bin/micromamba", "CONDA_PREFIX=/home/calvin/micromamba/envs/rmg_env", "JULIA_LOAD_PATH=@:@rmg_env:@stdlib", "SSH_AGENT_LAUNCHER=gnome-keyring", "MAMBA_ROOT_PREFIX=/home/calvin/micromamba", "WINDOWPATH=2", "LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:"]), ProcessExited(1)) [1]

```

Edit 2:

I have also attempted to recreate this issue on my local computer (Ubuntu 22.04) by installing micromamba as my package manager. I am also getting the same error as above, where it cannot find the configuration file. I am uncertain what that file is meant to be and why this issue is now appearing

**Comment by wholtz** [comment]
Hello @calvinp0 thank you for your interest in micromamba and for taking the time to report your issue.

Your build is not designed to be reproducible. Some steps towards reproducibility would include:

1.  `FROM` line would reference an image digest or at least a tag that specifies a version of `micromamba`.  
2.  `apt-get install` pins software versions. 
3. `environment.yml` from RMG-Py only pins version numbers for a fraction of the software installed.  Use [conda-lock](https://github.com/conda/conda-lock) to make conda environments reproducible.

Your build breaking could be due to any of those pieces of software having been updated since you last built the image.

Due to the complexity of your Dockerfile and environment, I'm not going to attempt to nail down the root-cause of your issue. With a bit of tweaking, I was able to get the `Pkg.build("PyCall")` step to complete.

```
# bring in the micromamba image
FROM mambaorg/micromamba:jammy

USER root

# Install and update APT; git cmake and build-essential are required for
RUN apt-get update && apt-get install -y \
    git \
    gcc \
    g++ \
    make \
    libgomp1\
    libxrender1 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER $MAMBA_USER

# Create a directory
RUN mkdir -p /home/$MAMBA_USER/Code
WORKDIR /home/$MAMBA_USER/Code

# Git clone the repo
RUN git clone https://github.com/ReactionMechanismGenerator/RMG-Py.git
RUN git clone https://github.com/ReactionMechanismGenerator/RMG-database.git

# Install RMG-Py
WORKDIR /home/$MAMBA_USER/Code/RMG-Py
RUN micromamba env create -f environment.yml -n rmg_env -y \
    && micromamba clean --all --yes
ARG MAMBA_DOCKERFILE_ACTIVATE=1
ENV ENV_NAME=rmg_env
# Compile RMG-Py
RUN make

RUN touch /opt/conda/envs/rmg_env/condarc-julia.yml

# Link Julia and python
RUN CONDA_JL_CONDA_EXE=/bin/micromamba julia -e 'using Pkg; Pkg.add("Conda"); Pkg.build("Conda");Pkg.add(PackageSpec(name="PyCall", rev="master")); Pkg.build("PyCall")'
```

**Comment by calvinp0** [comment]
Hi @wholtz! Thank you so much for the response and feedback.

I am new to creating Dockerfile but I have now added a image digest for 1.3.1 jammy. I will add software version pins from now on. Regarding the conda-lock, unfortunately the owners of RMG-Py have decided not to use a conda-lock for the time being but I will bring it up again with them in future discussions.

Regarding your solution, thank you! It is embarrassing that I didn't attempt that prior to posting my issue. I did come  up with another solution where I also set the env variable `CONDA_JL_HOME=/opt/conda/envs/rmg_env` and that seems to also make it work. I wouldn't be surprised if the real issue is that PyCall doesn't play well with micromamba.

Thanks again!

**Comment by lgonzalezsa** [comment]
Hi @wholtz,

I am trying to create a Containerfile that let me create an image with micromamba and install Julia to let me use Python as primary language and call Julia as needed.
I tried your solution:
```Docker
# Link Julia and python
RUN CONDA_JL_CONDA_EXE=/bin/micromamba julia -e 'using Pkg; Pkg.add("Conda"); Pkg.build("Conda");Pkg.add(PackageSpec(name="PyCall", rev="master")); Pkg.build("PyCall")'
```
I am using: FROM docker.io/mambaorg/micromamba:latest and using podman engine instead of docker.
During build I got:
```bash
WARN[0204] SHELL is not supported for OCI image format, [/usr/local/bin/_dockerfile_shell.sh] will be ignored. Must use `docker` format 
--> f843f7fb939c
STEP 15/24: RUN CONDA_JL_CONDA_EXE=/bin/micromamba julia -e 'using Pkg; Pkg.add("Conda"); Pkg.build("Conda");Pkg.add(PackageSpec(name="PyCall", rev="master")); Pkg.build("PyCall")'
/bin/sh: 1: julia: not found
Error: building at STEP "RUN CONDA_JL_CONDA_EXE=/bin/micromamba julia -e 'using Pkg; Pkg.add("Conda"); Pkg.build("Conda");Pkg.add(PackageSpec(name="PyCall", rev="master")); Pkg.build("PyCall")'": while running runtime: exit status 127
make: *** [Makefile:16: build] Error 127
```
Not sure why during build julia is not found, could be an environment PATH related issue?

If I go manually to the latest image layer and run the command in BASH, Julia is found, when executing I got the following error, seems micromamba does not expect `--satisfied-skip-solve`
Is this something new?

What could be the best way to have a Containerfile installing my Python environment and then Julia and the required packages to allow me to call Julia from Python kernel in a Jupyter Notebook or IPython session?

```bash
...
ERROR: Error building `PyCall`: 
The following argument was not expected: --satisfied-skip-solve
Run with --help for more information.
[ Info: Running `conda install -y --satisfied-skip-solve numpy` in root environment
...
```

**Comment by calvinp0** [comment]
Hi @lgonzalezsa 

The issue pertains to PyCall/Conda.jl. They implemented this skip solve argument recently. We also came across this problem a couple of weeks ago. 

We solved it by pointing Julia to Conda during the image build 

```

RUN CONDA_JL_CONDA_EXE=/bin/micromamba julia -e 'ENV["CONDA_JL_CONDA_EXE"]="/opt/conda/envs/rmg_env/bin/conda";using Pkg;Pkg.add(PackageSpec(name="PyCall", rev="master")); Pkg.build("PyCall"); Pkg.add(PackageSpec(name="ReactionMechanismSimulator", rev="main"))'

```

**Comment by lgonzalezsa** [comment]
I was reviewing the command you shared and seems the only difference with the one I was trying, is the `ENV["CONDA_JL_CONDA_EXE"]="/opt/conda/envs/rmg_env/bin/conda"` when invoking julia.
Seems you have conda binary? but in my case I am using micromamba and I do not have a conda binary. Also using the base env.
If I use `FROM python:3.11-slim-bullseye` and then use [Julia Dockerfile](https://github.com/docker-library/julia/blob/master/1.9/bullseye/Dockerfile) with the following lines at the end, my environment works, but sadly without micromamba.

```docker
# install PyJulia
RUN python -m pip install julia
RUN julia -e "using Pkg; pkg\"add PyCall\"; pkg\"precompile\";"
```

**Comment by calvinp0** [comment]
> I was reviewing the command you shared and seems the only difference with the one I was trying, is the `ENV["CONDA_JL_CONDA_EXE"]="/opt/conda/envs/rmg_env/bin/conda"` when invoking julia. Seems you have conda binary? but in my case I am using micromamba and I do not have a conda binary. Also using the base env. If I use `FROM python:3.11-slim-bullseye` and then use [Julia Dockerfile](https://github.com/docker-library/julia/blob/master/1.9/bullseye/Dockerfile) with the following lines at the end, my environment works, but sadly without micromamba.
> 
> ```
> # install PyJulia
> RUN python -m pip install julia
> RUN julia -e "using Pkg; pkg\"add PyCall\"; pkg\"precompile\";"
> ```

You are right, my apologies. I forgot I had to install conda into our environment in order to get Julia to work again with Python.

I believe they added in the `--satisified-skip-solve` in this PR: https://github.com/JuliaPy/Conda.jl/pull/241

So if you could install a version of Conda.jl, that could help deal with the issue in the short term.
