### ISSUE TITLE
issues with conda python

### ISSUE THREAD

**Issue by lhangart** [mamba-org/micromamba-docker#335]
Hi all, 

I built a container using your image. When I run it in the interactive mode, all goes well. However, wenn I run it with an entry point ENTRYPOINT ["/usr/bin/bash","./startFold.sh"], I get a python not found error. Any tips? ARG MAMBA_DOCKERFILE is set to 1

Thanks,

Lars

**Comment by wholtz** [comment]
Was on my phone before, now I can write a slightly longer response. 

You have overwritten the `ENTRYPOINT` that comes with the `mambaorg/micromamba` image.

Try doing this instead to incorporate both entrypoint scripts:

```Dockerfile
ENTRYPOINT ["/usr/local/bin/_entrypoint.sh", "/usr/bin/bash", "./startFold.sh"]
```

**Comment by lhangart** [comment]
Hi Will,

Thanks for the clarification. Is there a way to pass variables given with the docker command through entrypoint.sh to startFold.sh?

Lars

**Comment by maresb** [comment]
By variables do you mean command line parameters? Usually parameters get passed through as expected. If you're still having trouble perhaps you could share a more concrete example of what you mean?

**Comment by lhangart** [comment]
Hi Ben,

Thanks for your help. Yes, I would like to pass command line arguments to startFold.sh, however, $1 or ("$@") come up empty in startFold.sh
with
ENTRYPOINT ["/usr/local/bin/_entrypoint.sh", "./startFold.sh"]

Lars

**Comment by lhangart** [comment]
text after however should read _dollarsign_1 and ("_dollarsign_@")

**Comment by lhangart** [comment]
startFold.sh 
```#!/bin/bash
args_array=("$@")
for i in "${args_array[@]}"
do
  :
  echo "### Got variable $i ###"
done
echo Starting Fold with file $1
```

**Comment by wholtz** [comment]
In #343 , I added documentation about how to modify the `ENTRYPOINT`.

Here is an example of passing through command line arguments to the entrypoint script.

`my-addition.sh`:
```
#!/bin/bash
echo "$@"
```

```Dockerfile
FROM mambaorg/micromamba:1.4.9
COPY my-addition.sh /tmp/my-addition.sh
ENTRYPOINT ["/usr/local/bin/_entrypoint.sh", "/tmp/my-addition.sh"]
```

```console
$ docker build . -q -t  issue335:1
sha256:a5ca80067dfcac087982d1a560eded6f8c17bd82b0059464579bd75fdfcb7fcc
$ docker run -it --rm issue335:1 foobar
foobar
```
