### ISSUE TITLE
Document workaround for hang when using docker on macOS ARM 

### ISSUE THREAD

**Issue by corneliusroemer** [mamba-org/micromamba-docker#349]
I've encountered this previously known issue: https://github.com/mamba-org/mamba/pull/1873 of a hang of micromamba during a micromamba installation within a docker container running on macOS with ARM processor.

It would be great if the workaround `micromamba config set extract_threads 1 && micromamba install ...` could be added to the micromamba docker docs. It was a bit tricky to find for me.

See https://github.com/mamba-org/mamba/issues/1611#issuecomment-1652638847

**Comment by wholtz** [comment]
Thanks for the suggestion. Done in #350.

**Comment by corneliusroemer** [comment]
Excellent! For context, this seems to be the qemu bug that is the root cause.

It's been fixed but may apparently take years to percolate fully.

https://gitlab.com/qemu-project/qemu/-/issues/285#note_919207579

**Comment by corneliusroemer** [comment]
FWIW, I've posted a StackOverflow Q&A on this to make it easier to find/use and for others to comment if they have other workarounds: https://stackoverflow.com/questions/76778360/micromamba-install-gets-stuck-when-run-in-docker-container-on-arm-mac/76778361#76778361

**Comment by maresb** [comment]
Excellent, thanks a lot @corneliusroemer! This is a great service to the community.

**Comment by corneliusroemer** [comment]
@maresb I'm never quite sure whether self-Q&A on SO is a waste of time so I appreciate the feedback :) It's definitely happened that I got _out of spite_ downvotes when I answered my own question.

As you understand the issue more deeply than me, what do you think is the reason that the `export G_SLICE=always-malloc` workaround didn't work for me? Why do I still encounter the issue even though QEMU has the issue marked as "fixed"?

**Comment by maresb** [comment]
SO definitely requires thick skin. I don't think it's productive or healthy to worry about downvotes unless constructive feedback is provided. Just keep doing your own thing, ignore the haters, and keep being awesome.

While I spent a lot of time trying to isolate the problem and make it reproducible, I unfortunately have no understanding of the internals. @jonashaag is really good at the low-level stuff, so perhaps he has some insight.

**Comment by corneliusroemer** [comment]
I do wonder if it would make sense to put the `micromamba config set extract_threads 1` workaround more prominently in the docs - it may well be a good default to use for _all_ M1/M2 users who are working on amd64 containers with mamba.

What would be truly amazing is if this could be baked in to the mamba image, that it recognizes if you're using QEMU and automatically (but overwritably) sets extract threads to 1.

Or is the problem now as widespread as I may think? To me this currently looks like it might affect everyone doing what I did: build a bioconda docker container with amd64 on an M1 mac. Maybe I was just unlucky.

**Comment by maresb** [comment]
I don't have M1/M2, so I can't readily reproduce such issues.

> What would be truly amazing is if this could be baked in to the mamba image, that it recognizes if you're using QEMU and automatically (but overwritably) sets extract threads to 1.

Ya, agreed. We did think of this (https://github.com/mamba-org/mamba/issues/1611#issuecomment-1104898049), and I don't remember the details of why this wasn't implemented. Perhaps it deserves to be revisited?

**Comment by jonashaag** [comment]
I'm using amd64 on an M2 Mac on a regular basis and never had this problem. I don't know why.

I also don't know why that `G_SLICE` stuff doesn't work anymore, maybe something has changed in Qemu/Glib?

**Comment by corneliusroemer** [comment]
> I'm using amd64 on an M2 Mac on a regular basis and never had this problem. I don't know why.

@jonashaag Can you try it with the same dockerfile and the following environment.yml?

env.yml:
```
name: pangolin
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython>=1.74
  - minimap2>=2.16
  - pip
  - python>=3.7
  - snakemake-minimal!=7.30.2
  - gofasta
  - ucsc-fatovcf>=426
  - usher>=0.5.4
  - git-lfs
  - pip:
    - git+https://github.com/cov-lineages/pangolin-data.git
    - git+https://github.com/cov-lineages/scorpio.git
    - git+https://github.com/cov-lineages/constellations.git
```

```Dockerfile
FROM mambaorg/micromamba:1.4.9
COPY environment.yml /environment.yml
RUN micromamba create -vv -y -n pangolin -f /environment.yml
```

```bash
docker build . --platform linux/amd64 2>&1 | tee log.txt
```

Curious if you get the same issue or not if you run the same commands.
