### ISSUE TITLE
Install pip dependencies results a permission denied (libmamba Error opening for writing)

### ISSUE THREAD

**Issue by scku208** [mamba-org/micromamba-docker#356]
My environment.yaml:

```
name: base

channels:
  - conda-forge
  - anaconda
  
dependencies:
  - ipython
  # ... some modules...
  - SQLAlchemy
  - pip:
    - mpltw
    # - -r file:requirements.txt
```

when I run:
`docker compose build flask`
I got something like:
```
...
28.82 error    libmamba Error opening for writing "/mambafmGNjMtYFLS": Permission denied
28.82 error    libmamba Error opening for writing "/mambafmGNjMtYFLS": Permission denied
28.83 
28.83 Installing pip packages: mpltw
29.69 ERROR: Could not open requirements file: [Errno 2] No such file or directory: '/mambafmGNjMtYFLS'
30.12 critical libmamba pip failed to install packages
------
failed to solve: process "/usr/local/bin/_dockerfile_shell.sh micromamba install -y -n base -f /environment.yaml &&     micromamba clean --all --yes" did not complete successfully: exit code: 1
...
```

Without pip dependencies, everything worked.
Then I "exec bash" into container,  use command:
`ls -ld /`
Output:
`drwxr-xr-x 1 root root 4096 Aug  2 16:18 /`
So I think mamba cannot write the "mambafmGNjMtYFLS" file in there (/).

The workaround I tried:
Change Dockerfile from:
```
FROM mambaorg/micromamba:1.4
LABEL maintainer="wise@wisenvr.com" \
      wisenvr.release-date="2023-08-02" \
      wisenvr.version="0.1.0"

COPY --chown=$MAMBA_USER:$MAMBA_USER environment.yaml /environment.yaml

RUN micromamba install -y -n base -f /environment.yaml && \
    micromamba clean --all --yes

EXPOSE 8080/tcp
```
To:
```
FROM mambaorg/micromamba:1.4
LABEL maintainer="wise@wisenvr.com" \
      wisenvr.release-date="2023-08-02" \
      wisenvr.version="0.1.0"

COPY --chown=$MAMBA_USER:$MAMBA_USER environment.yaml /app/environment.yaml

RUN micromamba install -y -n base -f /app/environment.yaml && \
    micromamba clean --all --yes

EXPOSE 8080/tcp
```
I put the environment.yaml in /app which I mount and mambauser has permission to write
then it Works.

It's a bug or? 
Thanks.

btw, mamba-docker version 1.2 has no problem with pip dependency.

**Comment by wholtz** [comment]
Hi @scku208 . When there are pip packages in the environment definition, `micromamba` needs to write a temporary file. This used to be written to `/tmp/requirements.txt` but this could collide with an existing file [mamba #1894](https://github.com/mamba-org/mamba/issues/1894). Now a uniquely named temporary file is created instead. It appears this new temporary file goes into the same directory as the environment definition file (`environment.yaml`).  So write access is required to that directory. 

This is a `micromamba` issue and not a docker specific issue, so I'm going to close and create a new issue for the `micromamba` team.
