### ISSUE TITLE
Problem: Cannot add a corporate SSL certificate as update-ca-certificates tool was removed from the multistage final docker image

### ISSUE THREAD

**Issue by zoobab** [mamba-org/micromamba-docker#380]
Problem: I cannot add a corporate SSL certificate as the `update-ca-certificate` tool was removed from the micromamba multistage final docker image

A possible solution would be to copy the 4 files of update-ca-certificate tool:

https://manpages.ubuntu.com/manpages/xenial/man8/update-ca-certificates.8.html#files

**Comment by maresb** [comment]
Hi @zoobab, worry if I'm missing something obvious, but what's stopping you from adding this to your Dockerfile?

```Dockerfile
USER root
RUN apt-get update && apt-get install -y ca-certificates
USER $MAMBA_USER
```

**Comment by zoobab** [comment]
@maresb I am inside an environment not connected to the internet where 'apt-get update' is not possible.

**Comment by wholtz** [comment]
It is our policy that we stay as close to the base image as possible. Only packages required for micromamba and our helper scripts are added to the base image. The CA update tool does not qualify. 

I hope you can find another way to work within your constraints.

**Comment by maresb** [comment]
Ah, I see. Is anything stopping you from copying the 4 files yourself?
