### ISSUE TITLE
Update Docker Hub with a bullseye based image

### ISSUE THREAD

**Issue by vidosits** [mamba-org/micromamba-docker#42]
Hey @wholtz , when do you think there will be a release to Docker Hub with a Debian Bullseye based image?

Thanks in advance!

**Comment by vidosits** [comment]
Ah, I guess it's based on (micro)mamba releases, right? Maybe a tag with a new build version could be possible?

**Comment by wholtz** [comment]
Hi @vidosits -- thanks for your interest in micromamba.

Mamba 0.16.0 was released a couple of hours ago. If all goes well, a new image (based on bullseye) will be on docker hub within 24 hours.

It probably would be a good idea to build images for all the debian releases that have not yet reached end of life.

**Comment by vidosits** [comment]
Thanks @wholtz, very helpful! Lucky, that a new Mamba release just dropped :)

**Comment by wholtz** [comment]
@vidosits after a few hiccups, the 0.15.3 version on dockerhub has been updated to a bullseye based image. 0.16.0 version is not yet on dockerhub as the docker build currently only works when all 3 supported architectures have their binaries available on conda-forge and ppc64le binary has not made it to conda-forge yet.

**Comment by vidosits** [comment]
@wholtz thanks, I just tried the :latest one, works great!
