### ISSUE TITLE
Apache 2.0 License missing copyright owner information

### ISSUE THREAD

**Issue by pranavmishra90** [mamba-org/micromamba-docker#435]
Hopefully this should be a quick fix... The [Apache 2.0 license file](https://github.com/mamba-org/micromamba-docker/blob/0ddd94be42766f662257f45e078a87a1ffafb509/LICENSE) is missing the author information:

```sh
# Line 189
   Copyright [yyyy] [name of copyright owner]
```

I'm using this docker image as part of another image, and I'd like to give proper credit. Thanks you for providing this incredible docker image!

**Comment by wholtz** [comment]
Thanks for the heads up @pranavmishra90 . I appreciate your desire to give credit.
