### ISSUE TITLE
alpine:3.19 does not work as BASE_IMAGE

### ISSUE THREAD

**Issue by FrancescoNegri** [mamba-org/micromamba-docker#480]
Hi! First of all thank you for your time and effort in managing this repo!

I am trying to create an image coincident with the standard micromamba-docker one, but with the first line of the Dockerfile modified as follow:
```docker
ARG BASE_IMAGE=alpine:3.19
```
According to my understanding of micromamba-docker Dockerfile, using Alpine as the base image should be supported. As a matter of fact, the image builds sucsessfully, but I cannot run a container due to errors in the `_activate_current_env.sh` script, that is automatically launched by the entrypoint.

The error I receive is:
```sh
/usr/local/bin/_activate_current_env.sh: line 8: /bin/micromamba: cannot execute: required file not found
/usr/local/bin/_activate_current_env.sh: line 35: /bin/micromamba: cannot execute: required file not found
```

I have seen that on DockerHub you have tags targeting Alpine and they work alright. Thus, I am not understanding what I am getting wrong. Thank you in advance for your help!

**Comment by maresb** [comment]
@FrancescoNegri, Micromamba requires glibc. Could you try instead

```
ARG BASE_IMAGE=frolvlad/alpine-glibc:alpine-3.19
```

By the way, we have pre-built images for Alpine 3.19. Could `mambaorg/micromamba:alpine3.19` meet your needs?

**Comment by FrancescoNegri** [comment]
Thank you for your reply! The issue is that I am trying to build your image on top of `docker:dind`, which uses alpine:3.19, that's why I cannot use your pre-built image.

**Comment by FrancescoNegri** [comment]
@maresb thank you once again for your help. I managed to build my image by including the commands executed in `frolvlad/alpine-glibc:alpine-3.19` Dockerfile.

**Comment by maresb** [comment]
Glad you got it working @FrancescoNegri!

In case you need to do something similar in the future, you may find it easier to follow [this guide](https://micromamba-docker.readthedocs.io/en/latest/advanced_usage.html#adding-micromamba-to-an-existing-docker-image).

**Comment by FrancescoNegri** [comment]
Thank you for your suggestion, you're right, I didn't look into that guide, it would have surely been helpful. Have a nice day :)
