### ISSUE TITLE
Images now available from mambaorg/micromamba

### ISSUE THREAD

**Issue by wolfv** [mamba-org/micromamba-docker#5]
Hi @wholtz 

I have completed the github action pipeline now, and we build & push (automatically) the freshest releases to `mambaorg/micromamba` now.

Is it OK for you if we change the reference in the readme? I made you a maintainer of that image as well.

The github action checks for a new release every 6 hours and pushes one if there is a release.

**Comment by wholtz** [comment]
Done in 199c22722bfd4543e4ee8fe854a85d700b72bdac.
