### ISSUE TITLE
Updates for micromamba 2.x

### ISSUE THREAD

**Issue by wholtz** [mamba-org/micromamba-docker#526]
@maresb please do not release micromamba-docker with micromamba 2.0 yet.

I want to use the breaking release  to make two changes and I'll need a little time to get them ready.
1. Ubuntu tags will transition from names to numbers (`nobel`-> `24.04`)
2. Add support for Amazon Linux as a base image.  This is a non-debian based image, so it involves some significant changes.

**Comment by maresb** [comment]
Got it. Awesome, thanks @wholtz!!!

**Comment by wholtz** [comment]
The v2.0.2 images are now up on dockerhub and ghcr.

The tag listing on Dockerhub is incomplete and the following tags are missing:
* alpine
* debian
* debian-slim
* ubuntu
* amazon
* cuda

**Comment by wholtz** [comment]
missing tags fixed in #549.
