### ISSUE TITLE
Use micromamba linked to musl-c for alpine image instead of alpine-glibc

### ISSUE THREAD

**Issue by vincent-pollet** [mamba-org/micromamba-docker#559]
Hello,

I have been using the micromamba images in many projects with great success ! However I ran into the following issue with the alpine containers: Apptainer crashes with a segmentation fault when running the micromamba alpine image on a almalinux 9 host. Actually the issue is happening with the base image `frolvlad/alpine-glibc:alpine-3.20` from which the micromamba container is build. The issue was reported to apptainer [here](https://github.com/apptainer/apptainer/issues/2533).

Quoting the [sgerrand](https://github.com/sgerrand), a maintainer of the `frolvlad/alpine-glibc:alpine-3.20` image: 

> I strongly recommend migrating away from depending the glibc package for Alpine Linux and either update your software to use musl-c or change Linux distributions to one based on the GNU C library.

It appears that the use of the `alpine-glibc` image is not recommended. Would it be possible to compile micromamba against musl-c, and use that to build the micromamba alpine containers ?

Thank you!

**Comment by wholtz** [comment]
Hello @vincent-pollet . It is known that using glibc on top of Alpine Linux is not fully compatible with all software that uses glibc. This is why in [our documentation](https://micromamba-docker.readthedocs.io/en/latest/image_size.html) we recommend additional testing when using our alpine-based images:

> Our alpine-based images come pre-loaded with glibc, which should enable them to run most conda packages, but extra testing is recommended when using the alpine-based images.

Compiling `micromamba` against musl-c is not the solution you are hoping for, as almost all conda packages are complied against glibc.  I would suggest moving to one of our images based on `debian:slim` such as `micromamba:debian12-slim`. This image is still fairly small and is built from a  glibc-based LInux distribution.

**Comment by vincent-pollet** [comment]
> Compiling micromamba against musl-c is not the solution you are hoping for, as almost all conda packages are complied against glibc

Ok now I understand. Thanks a lot for the explanation! I will use a `debialn:slim` image as you suggest

Thank you!
