### ISSUE TITLE
Error when mamba.sh exists

### ISSUE THREAD

**Issue by maresb** [mamba-org/micromamba-docker#57]
Whenever `micromamba shell hook -s bash` is executed and `$MAMBA_ROOT_PREFIX/etc/profile.d/mamba.sh` exists, then the output seems to be `mamba.sh`. The standard `mamba.sh` initialization script defines only the `mamba()` shell function, leaving `conda()` and `micromamba()` undefined.

### EDIT: while the issue described immediately below has a workaround, the comment https://github.com/mamba-org/micromamba-docker/issues/57#issuecomment-996556375 illustrates the latest breakage.

The `entrypoint.sh` for this image calls

```bash
eval "$(/bin/micromamba shell hook -s bash)"
micromamba activate "$ENV_NAME"
```
If `mamba.sh` exists (for example if the user installs `mamba`), then the `micromamba` command above refers to the binary instead of the shell function, it results in the following error message:
```
The following arguments were not expected: base activate
Run with --help for more information.
```

To reproduce, use either of these Dockerfiles:

```Dockerfile
FROM mambaorg/micromamba:0.18.2

RUN micromamba install -c conda-forge --prefix=$MAMBA_ROOT_PREFIX mamba
```
```Dockerfile
FROM mambaorg/micromamba:0.18.2

RUN mkdir -p /opt/conda/etc/profile.d/ \
  && echo "echo Ran mamba.sh" > /opt/conda/etc/profile.d/mamba.sh
```

and then run
```bash
docker build . -t micromamba-docker-issue-57
docker run --rm -it micromamba-docker-issue-57
```
and you will see the output
```
Ran mamba.sh
The following arguments were not expected: base activate
Run with --help for more information.
```

It seems to me like the proper fix should probably be upstream in micromamba to ensure that `micromamba()`, `mamba()`, and `conda()` are always defined in the shell init. For example, maybe it should ignore `mamba.sh`, or use `mamba.sh` and append the definition of `micromamba()`?

**Comment by wholtz** [comment]
HI @maresb. Thanks for the detailed report. This is related to the problems being discussed in #55.

**Comment by wholtz** [comment]
@maresb - after looking into this some more, I am in agreement with you that a clean solution will likely involve upstream changes to micromamba or mamba. Could you please post an issue in the upstream repo: https://github.com/mamba-org/mamba ?

**Comment by wholtz** [comment]
Fixed with #69

**Comment by maresb** [comment]
Thanks @wholtz!

**Comment by wholtz** [comment]
Thank you @maresb for the PR and tests!

**Comment by wholtz** [comment]
I am opposed to invalidating image digests once they are on dockerhub (with the exception of severely broken images). Because the image releases are based on micromamba version numbers, the current build system does not allow me post a new build without invalidating the existing digests for the current version. 

We could discuss modifying our tagging convention to allow for additional releases that are not based on new micromamba versions. We would need to have some clear and systematic way of tagging all images. The build scripts would need to be tweaked to allow for new tags as well.

**Comment by maresb** [comment]
Ah, ok, thanks for explaining. I've seen other projects solve this by tagging with the git hash, e.g. [here](https://hub.docker.com/r/jupyter/base-notebook/tags). Would it make sense to implement such a scheme for the next micromamba release? (It sounds like in any case we need to wait for a new release.)

**Comment by maresb** [comment]
@wholtz, could we please reopen this until it's fixed? Thanks to our recent progress, I managed to provide a MWE and a more detailed explanation: https://github.com/mamba-org/mamba/issues/1322#issuecomment-996018095

**Comment by maresb** [comment]
The latest breaking example related to these issues:

```Dockerfile
FROM mambaorg/micromamba:git-8c29016

RUN micromamba install -y -c conda-forge --prefix=$MAMBA_ROOT_PREFIX mamba
RUN micromamba install -y -c conda-forge --prefix=$MAMBA_ROOT_PREFIX zipp
```

Running `docker build .` results in

```
...
Finished zipp                                 (00m:00s)              12 KB     46 KB/s

Transaction starting
Linking zipp-3.6.0-pyhd8ed1ab_0
The following arguments were not expected: /opt/conda activate
Run with --help for more information.
Transaction finished
Removing intermediate container 3defda657e23
 ---> 7dd11b21ced9
Successfully built 7dd11b21ced9
```
Note the error:
```
The following arguments were not expected: /opt/conda activate
Run with --help for more information.
```
This error is caused by https://github.com/mamba-org/mamba/issues/1358.

**Comment by maresb** [comment]
@wholtz, could we please reopen this until the next micromamba release drops? (It was auto-closed on the upstream fix.) Thanks!

**Comment by maresb** [comment]
All better now. This new version is awesome!!! :smile:

**Comment by wolfv** [comment]
yay :)

**Comment by wolfv** [comment]
Thanks for your contributions @maresb and sorry for the slow merge times :)

I think the next release will be even better ... @chrisburr uncovered a way to reduce linking times through aggregated python compilation over on https://gitter.im/mamba-org/Lobby :)

**Comment by maresb** [comment]
That's so amazing! You and Chris are my open-source heroes. :blush: 

I'm really excited about all the possibilities enabled by this combination of micromamba and docker. In my opinion, miniconda is as of now obsolete!

**Comment by wholtz** [comment]
@maresb - can we now remove this hack?
https://github.com/mamba-org/micromamba-docker/blob/5bd26ad79abc85cbcfec4d123832209a8382894c/_activate_current_env.sh#L10

**Comment by maresb** [comment]
@wholtz, great point, I had forgotten about that! I hope so. Let me run a few tests...
