### ISSUE TITLE
Feature request: publish also Ubuntu base image

### ISSUE THREAD

**Issue by maresb** [mamba-org/micromamba-docker#59]
Could we also publish an image based on `ubuntu:20.04` (focal)?

**Comment by wholtz** [comment]
Assuming someone else doesn't step up with a PR, my current roadmap for expanding the number of base images is as follows:

1. Add all releases of debian slim that have not yet reached LTS end of life (ie, bullseye, buster, stretch)
2. Add the non-slim debian image
3. Add other debian based distros that have community interest (such as ubuntu)
4. Add non-debian based distros that have community interest

The build and test infrastructure need to be altered to support additional base images. I have been slowly working on this.

**Comment by wholtz** [comment]
Done in 95a41ce32497628528c90922221d1f82da3c1f44 and 2b911d21f8fa19f349752fe0c67242b6a1dbb9b2

**Comment by maresb** [comment]
Wow, very nice @wholtz!!! Thanks so much for all your work on this!

In addition to being directly useful, it's really great for reference to see how you made everything, e.g. with the CI.
