### ISSUE TITLE
Add PPC64LE docker image

### ISSUE THREAD

**Issue by wolfv** [mamba-org/micromamba-docker#6]
I think it should now be easy to also build a docker image for ARM64 Linux.
Basically the same process, just using a different URL for micromamba (linux-aarch64) and base image.

**Comment by wolfv** [comment]
And even PPC64LE if we want to.

**Comment by wholtz** [comment]
Added PCC64LE build in dea0fd86b365862d3afd2e55b99f79785e506289. I am going to leave this open until the next mamba release, so that I can verify the production builds go as expected.

**Comment by wolfv** [comment]
Nice!

**Comment by wholtz** [comment]
PPC64LE image for micromamba v0.15.3 is up on dockerhub. Closing.
