### ISSUE TITLE
Consider not initing the environment for root/user

### ISSUE THREAD

**Issue by maresb** [mamba-org/micromamba-docker#70]
In the spirit of #61, I wonder if we should eliminate the `init` and `activate` commands for the `root` and `micromamba` users in the Dockerfile.

Even though we activate by default in our `ENTRYPOINT`, this feels to me like it could be a bit extreme.

A middle ground might be (in the context of #69)

```bash
echo "source _activate_current_env.sh" >> ~/.bashrc
```

At least this way it would work in case `MAMBA_ROOT_PREFIX` changes.

**Comment by wholtz** [comment]
Removing the `init` and `activate` commands from the Dockerfile will result in 2 tests failing.

I think it does make sense to continue the consolidation of the activation code and use your 'middle ground' solution.

**Comment by wholtz** [comment]
done via 'middle ground' implementation in #81
