### ISSUE TITLE
Images generated in tests should be tagged micromamba:test-name

### ISSUE THREAD

**Issue by maresb** [mamba-org/micromamba-docker#89]
A quick (not necessarily accurate) skim of my `docker image ls` shows a whole lot of superfluous tags generated by the test suite:
```
run-exec-form
run-shell-form
different-user
new-user 
cmd-shell-form
cmd-exec-form
cli-invocations
mamba-1322-workaround
multi-env
```
We should probably be tagging these as `micromamba:test-run-exec-form`, etc.

I'd submit a PR to fix this, but there are already enough merge conflicts in my current PRs. :stuck_out_tongue_closed_eyes:

**Comment by wholtz** [comment]
I agree. I tend to regularly blow all my images away, so I haven' t really noticed.

**Comment by wholtz** [comment]
Done in #111
