### ISSUE TITLE
Dockerhub secrets not being passed when push_latest is run by non-admins

### ISSUE THREAD

**Issue by maresb** [mamba-org/micromamba-docker#90]
![image](https://user-images.githubusercontent.com/15216687/146259603-f8a80e9b-05bb-40de-965c-b4c55602e2ad.png)

**Comment by wholtz** [comment]
Nothing has changed, so I'm surprised by this. I have verified the docker/login-action has not had a recent commit and the secrets still exists. I think either something at GitHub broke that is preventing the secrets from being sent or Dockerhub is having some sort of authentication issue. Either way I don't think there is an action I can take.

**Comment by wholtz** [comment]
I manually triggered a the push_latest action and it worked. I have not altered anything. I am unsure if the different trigger action mattered or if something resolved in the past several hours. I am going to close this issue for now and it can be re-opened if the same error pops up in the next few days.

**Comment by maresb** [comment]
@wholtz, I think I see what's wrong here.

Look carefully at the branch names for all the failed builds. They all start with `maresb:`. This must be somehow running on my fork. No idea how to fix this. :laughing: 

![image](https://user-images.githubusercontent.com/15216687/146408679-77a43f07-2465-4cfc-b640-7faf1be92f40.png)

**Comment by wholtz** [comment]
Yes, I was just about to post the same observation.  I'm also not sure of the solution, but it gives me some clues as to what I need to read up on.

**Comment by wholtz** [comment]
The [GitHub Actions Docs](https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow) contain this:

> Note: With the exception of GITHUB_TOKEN, secrets are not passed to the runner when a workflow is triggered from a forked repository.

**Comment by wholtz** [comment]
fixed in 8c29016
